### ISSUE TITLE
web_sys::ImageData Constructor is Not Sound

### ISSUE THREAD

**Issue by anlumo** [rustwasm/wasm-bindgen#2445] opened 2021-02-04 14:37 UTC
### Describe the Bug

The two constructors for web_sys::ImageData take a `Clamped<&[u8]>`, which is a reference. However, ImageData does *not* copy this data to its own buffer, so the resulting JS object depends on local data in a way that the Rust compiler is not aware of it.

### Steps to Reproduce

Example code:
```rust
use wasm_bindgen::Clamped;
use web_sys::ImageData;

#[wasm_bindgen]
pub fn foo() -> ImageData {
    let bitmap = vec![0u8; 100 *100 * 4];
    ImageData::new_with_u8_clamped_array_and_sh(Clamped(&bitmap), 100, 100)
}
```

Then use that code in a wasm module and call it from JavaScript. In JavaScript, store that ImageData and use it for a while.

### Expected Behavior

The ImageData stays the same.

### Actual Behavior

After a few operations on the wasm side, data corruption in the ImageData occurs.

In our project, it looks like this:
![image](https://user-images.githubusercontent.com/644763/106907265-5b096200-66fe-11eb-9d80-8c7d277af113.png)

The noise above used to be proper text.

### Additional Context

A workaround would be to create a new Uint8ClampedArray and store it there, since then the JS runtime is responsible for memory management. However, unlike in JavaScript directly, in web_sys there is no constructor exposed that can take a Uint8ClampedArray.

What works for me is to return a Uint8ClampedArray, width and height from the function instead and construct the ImageData on the JavaScript side. However, this is not a general solution since sometimes you might want to use the ImageData directly in Rust.

Also, the two constructors of ImageData exposed right now should be marked as unsafe, since they're not making sure that the data referenced is staying alive during the runtime of the ImageData.

**Comment by anlumo** [comment] 2021-02-04 14:37
Related to #423

**Comment by daxpedda** [comment] 2024-11-07 19:08
Closing as duplicate of #423.

**Closed by daxpedda** 2024-11-07 19:08 UTC
Labels: bug
