### ISSUE TITLE
wasm file schema version: 0.2.84 (153a6aa9c) != 0.2.84

### ISSUE THREAD

**Issue by ms140569** [rustwasm/wasm-bindgen#3406] opened 2023-04-26 12:52 UTC
Hi *,

when trying to run the hello_world demo (wasm-bindgen/examples/hello_world) from wasm-bindgen 153a6aa9c7a989c1865df7f93b2ddbca1113a175 like this:

npm run serve

I get this error:

[INFO]: 🌀  Compiling to Wasm...
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
error:

it looks like the Rust project used to create this wasm file was linked against
version of wasm-bindgen that uses a different bindgen format than this binary:

  rust wasm file schema version: 0.2.84 (153a6aa9c)
     this binary schema version: 0.2.84

I've tried both fixes:

cargo update -p wasm-bindgen
cargo install -f wasm-bindgen-cli

without any success.

What can i do to fix this?

PS: It's a MacBook M1/ARM64 with:

OS: v12.5.1
rustc 1.69.0 (84c898d65 2023-04-16)
wasm-bindgen 0.2.84
wasm-pack 0.11.0

**Comment by ms140569** [comment] 2023-04-26 13:49
OK, my one is duplicate of:

https://github.com/rustwasm/wasm-bindgen/issues/3379

We might place a warning in the main README.md.

Sorry for the noise ..

**Comment by daxpedda** [comment] 2023-05-12 20:56
Duplicate of https://github.com/rustwasm/wasm-bindgen/issues/2619.

**Closed by daxpedda** 2023-05-12 20:56 UTC
Labels: bug
