### ISSUE TITLE
webidl-tests/global.rs test fails

### ISSUE THREAD

**Issue by alexlapa** [rustwasm/wasm-bindgen#1354] opened 2019-03-15 20:17 UTC
### Describe the Bug

`crates/webidl-tests/global.rs` test fails on Ubuntu (18.04.2 / 18.10) with following message:

```
error[E0428]: the name `__WASM_BINDGEN_GENERATED_1d041a847919c908` is defined multiple times
   --> /home/alexlapa/CLionProjects/wasm-bindgen-fork/target/wasm32-unknown-unknown/debug/build/webidl-tests-54f588f47d44762e/out/global.rs:359:1
    |
359 | pub static __WASM_BINDGEN_GENERATED_1d041a847919c908: [u8; 490usize] = {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `__WASM_BINDGEN_GENERATED_1d041a847919c908` redefined here
    | 
   ::: crates/webidl-tests/global.rs:7:1
    |
7   | #[wasm_bindgen]
    | --------------- previous definition of the value `__WASM_BINDGEN_GENERATED_1d041a847919c908` here
    |
    = note: `__WASM_BINDGEN_GENERATED_1d041a847919c908` must be defined only once in the value namespace of this module

error: aborting due to previous error

For more information about this error, try `rustc --explain E0428`.
error: Could not compile `webidl-tests`.

```

### Steps to Reproduce

Run `WBINDGEN_I_PROMISE_JS_SYNTAX_WORKS_IN_NODE=1 cargo test -p webidl-tests --target wasm32-unknown-unknown` on Ubuntu.

I can build and provide Docker image, if that helps.

### Additional Context

1. Other tests work fine.
2. Env on failing machines:

```
$ wasm-pack --version
wasm-pack 0.6.0
```

```
$ rustc -V
rustc 1.35.0-nightly (bc44841ad 2019-03-14)
```

```
$ node -v
v10.15.3
```

3. It works on MacOS (same versions of specified tools).
4. Generated `out/global.rs`: https://www.diffchecker.com/mA1ufA1h

**Comment by alexcrichton** [comment] 2019-03-18 18:11
Hm I'm having trouble reproducing this locally on Linux as well. Can you run `rustup update nightly` and try again? Additionally can you gist `rustc -vV`?

**Comment by alexlapa** [comment] 2019-03-20 12:19
@alexcrichton ,

```
$ rustc -vV
rustc 1.35.0-nightly (bc44841ad 2019-03-14)
binary: rustc
commit-hash: bc44841ad2a2ad5f6c5e67b9e35ed8e7e71d4dc7
commit-date: 2019-03-14
host: x86_64-unknown-linux-gnu
release: 1.35.0-nightly
LLVM version: 8.0
```

After `rustup update nightly`

```
$ rustc -vV
rustc 1.35.0-nightly (3eb4890df 2019-03-19)
binary: rustc
commit-hash: 3eb4890dfe6db0279fdd3cda19f9643873ae3db9
commit-date: 2019-03-19
host: x86_64-unknown-linux-gnu
release: 1.35.0-nightly
LLVM version: 8.0
```

Still crashes. I will create Docker image and link it here.

**Comment by alexlapa** [comment] 2019-03-20 17:25
@alexcrichton ,

Dockerfile:
```
FROM ubuntu:18.10

ENV WBINDGEN_I_PROMISE_JS_SYNTAX_WORKS_IN_NODE 1
ENV PATH "$PATH:/root/.cargo/bin/"

RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly \
    && rustup target add wasm32-unknown-unknown --toolchain nightly \
    && git clone https://github.com/rustwasm/wasm-bindgen.git

WORKDIR /wasm-bindgen

CMD cargo test -p webidl-tests --target wasm32-unknown-unknown
```
No node of geckodriver, since it fails earlier. It is published, so you can just do `docker run alexlapa/wasm-test-fail:latest`.

**Comment by alexcrichton** [comment] 2019-03-20 17:33
Hm something very fishy is going on? I created `Dockerfile` with the above and ran:

```
$ docker build -t tag .
$ docker run -it tag
```

and it didn't fail in the expected place (went on to build `wasm-bindgen` and failed because OpenSSL wasn't installed). I also ran `docker run alexlapa/wasm-test-fail:latest` and it "succeeded" in that it failed the same place as the local image, not the expected place.

Can you gist a transcript of the commands you ran to get the bug?

**Comment by alexlapa** [comment] 2019-03-20 18:14
@alexcrichton,

So i've added `pkg-config` and `libssl-dev` to image, ie:
<details>

```dockerfile
FROM ubuntu:18.10

ENV WBINDGEN_I_PROMISE_JS_SYNTAX_WORKS_IN_NODE 1
ENV PATH "$PATH:/root/.cargo/bin/"

RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    pkg-config \
    libssl-dev

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly \
    && rustup target add wasm32-unknown-unknown --toolchain nightly \
    && git clone https://github.com/rustwasm/wasm-bindgen.git

WORKDIR /wasm-bindgen

CMD cargo test -p webidl-tests --target wasm32-unknown-unknown
```

</details>

Published as `alexlapa/wasm-test-fail:2`.

And ran it on 3 machines(2 Ubuntu and Mac). Only one Ubuntu fails with that "redefined here" message.  So yeah, i got single image that behaves differently. I guess, issue can be closed, since it is not really reproducible in other environments. Anyway, i will post update when i will resolve it (or not, if i will decide to reinstall Ubuntu on failing machine).

**Comment by alexcrichton** [comment] 2019-03-20 18:48
Hm so in theory if docker is not reproducible this could be a kernel difference between the two machines. Despite that though I'm not actually sure how we could cause kernel differences to show up here...

**Comment by alexcrichton** [comment] 2019-04-16 17:57
This is a bit old now so I'm gonna go ahead and close this, but let us know if this resurfaces!

**Closed by alexcrichton** 2019-04-16 17:57 UTC
Labels: bug
