### ISSUE TITLE
`WebSocket::send_with_u8_array` is broken with `atomics, bulk-memory` WASM features /SharedArrayBuffer WASM memory

### ISSUE THREAD

**Issue by r58Playz** [rustwasm/wasm-bindgen#4101] opened 2024-09-04 04:12 UTC
### Describe the Bug

When using the Atomics and Bulk Memory WASM features (`SharedArrayBuffer` WASM memory) `WebSocket::send_with_u8_array` throws an error from wasm-bindgen code. This can be worked around with a sed to create a `Uint8Array` from the WASM array, but that's obviously not clean.

[Workaround example](https://github.com/MercuryWorkshop/epoxy-tls/blob/9d1604cc3ea9af90e72de819556e91748141d732/client/build.sh#L60-L61)

Edit: This seems similar to #3772.

### Steps to Reproduce

Run `build.sh` and `serve.py` in this repository and put a WebSocket server on `localhost:4000`: https://github.com/r58Playz/wasm-bindgen-ws-bug

### Expected Behavior

`WebSocket::send_with_u8_array` should function properly.

### Actual Behavior
This error:

Chrome:
![Chrome error](https://github.com/user-attachments/assets/7ec13dca-3e59-44f3-a5be-c923cc73b4fd)

Firefox:
![Firefox error](https://github.com/user-attachments/assets/9ca45876-cc8f-484a-80f2-6cc0f51912d9)

WebKit:
![image](https://github.com/user-attachments/assets/6f2f206a-f931-47d6-9bd1-8fa49e9b01f3)

### Additional Context
None

**Comment by daxpedda** [comment] 2024-09-07 16:19
Duplicate of #3772.
I put it in my backlog, so hopefully I will get to it soon.

**Closed by daxpedda** 2024-09-07 16:19 UTC
Labels: bug
