### ISSUE TITLE
Webpack bundle problem

### ISSUE THREAD

**Issue by barabulkit** [rustwasm/wasm-bindgen#1979] opened 2020-01-26 01:30 UTC
### Summary

When i use the bundle created with webpack i always got this error:
Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

### Additional Details

here is generated code where is the error happens: 
```javascript if(importObject instanceof Promise && typeof WebAssembly.compileStreaming === 'function') {
/******/      promise = Promise.all([WebAssembly.compileStreaming(req), importObject]).then(function(items) {
/******/       return WebAssembly.instantiate(items[0], items[1]);
/******/      });
/******/     } else if(typeof WebAssembly.instantiateStreaming === 'function') {
                                                //we go here and then the error is happening
/******/      promise = WebAssembly.instantiateStreaming(req, importObject);
/******/     } else {
/******/      var bytesPromise = req.then(function(x) { return x.arrayBuffer(); });
/******/      promise = bytesPromise.then(function(bytes) {
/******/       return WebAssembly.instantiate(bytes, importObject);
/******/      });
/******/     }
```

if i remove the else if branch, everything works fine. but there is a problem that i need to do this everytime when i rebuild the bundle, is there anyway to fix this?

**Comment by Pauan** [comment] 2020-01-26 01:47
This is a problem with your server. Your server needs to give the `application/wasm` MIME type for `.wasm` files. What server are you using?

**Comment by barabulkit** [comment] 2020-01-26 06:07
i am using it with spring boot, inside thymeleaf templates

**Comment by Pauan** [comment] 2020-01-26 09:20
Okay, so you should try something [like this](https://stackanswers.net/questions/spring-boot-static-resources-and-mime-type-configuration):

```java
@Configuration
public class HbbtvMimeMapping implements WebServerFactoryCustomizer<ConfigurableServletWebServerFactory> {
    @Override
    public void customize(ConfigurableServletWebServerFactory factory) {
        MimeMappings mappings = new MimeMappings(MimeMappings.DEFAULT);
        mappings.add("wasm", "application/wasm");
        factory.setMimeMappings(mappings);
    }
}
```

(Also, to be clear, it's the *browser* that requires the `application/wasm` MIME type, so it's a browser error, not a wasm-bindgen error)

**Comment by alexcrichton** [comment] 2020-01-26 18:39
Thanks for the report! I believe the issue is as @Pauan pointed out, so I'm goign to close this

**Closed by alexcrichton** 2020-01-26 18:39 UTC
Labels: question
