### ISSUE TITLE
Explicitly add ".wasm" extension when importing wasm file in bundle target

### ISSUE THREAD

**Issue by qt911025** [rustwasm/wasm-bindgen#1441] opened 2019-04-11 11:51 UTC
## 💡 Feature description
When Parcel resolves generated pkg as a dependency, it cannot recognize "generated_pkg_bg" as a wasm file like what Webpack can do. Adding wasm extension explicitly can archive the compatibility.

There are plugins and built-in support in Parcel to resolve rs file or "Cargo.toml" directly, but this is fit for building components in a project, not for using package. Besides, Parcel encapsulate the pack so WebAssembly memory cannot be manipulated (I can still come back and import the generated bindgen file).

#### 💻 Basic example
In generated "my_pkg.js" (bundle target)
```js
import * as wasm from './my_pkg_bg';
```
⬇️
```js
import * as wasm from './my_pkg_bg.wasm';
```

**Comment by alexcrichton** [comment] 2019-04-11 13:58
Thanks for the report! This has historically been brought up in https://github.com/rustwasm/wasm-bindgen/issues/1133 and https://github.com/rustwasm/wasm-bindgen/pull/1059, but it's unfortunately pretty tricky to do for various reasons. In any case I've moved this issue over to the wasm-bindgen repo as I think the issue is with wasm-bindgen, not wasm-pack.

**Comment by ibaryshnikov** [comment] 2019-07-08 00:36
@alexcrichton are there any blockers for this update? There are situations when it's hard or impossible to modify `weblack.config.js`, and if `.wasm` is not explicitly mentioned as an allowed extension, the module would fail to load with an error like `can't resolve 'my_module_bg'`. We would fix a number of problems if use explicit extension

**Comment by Pauan** [comment] 2019-07-08 08:42
@ibaryshnikov What version of Webpack are you using? It's not necessary to change the `webpack.config.js`, because Webpack [already includes `.wasm` by default](https://webpack.js.org/configuration/resolve/#resolveextensions).

**Comment by ibaryshnikov** [comment] 2019-07-08 09:51
@Pauan angular 8, webpack 4.35.2
It doesn't work out of the box in angular, my bet is that they overload `resolve.extensions` somehow, and there's no access to `wabpack.config.js` there

**Comment by ibaryshnikov** [comment] 2019-07-08 09:56
@Pauan as it was mentioned by @marienz in this [comment](https://github.com/rustwasm/wasm_game_of_life/issues/47#issuecomment-508930085), [here's](https://github.com/angular/angular-cli/blob/560ba2a5dd32801bd4d95e0f2fa4f14493358eaa/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L362) a possible reason:
```javascript
extensions: ['.ts', '.tsx', '.mjs', '.js'],
```

**Comment by Pauan** [comment] 2019-07-08 10:02
@ibaryshnikov Ah, right, Angular uses its own config, and hides `webpack.config.js`, quite annoying.

This should of course be fixed on Angular's side, but I'm *also* in favor of fixing it on our side too.

If I remember correctly, the reason we didn't do this earlier is because it was causing issues with tests, or something like that. So if all of that is resolved (and @alexcrichton gives the OK), then yeah let's fix this.

**Closed** 2019-07-08 15:51 UTC
