### ISSUE TITLE
wasm-pack panics on webaudio example

### ISSUE THREAD

**Issue by wattux** [rustwasm/wasm-bindgen#2177] opened 2020-06-01 19:52 UTC
### Describe the Bug

Trying to build `./examples/webaudio` results in a panic at step `[INFO]: Installing wasm-bindgen..`, after cargo states a finished compilation:

```
[....]
Compiling web-sys v0.3.40 (/home/wattux/src/rust/wasm-bindgen/crates/web-sys)
Compiling webaudio v0.1.0 (/home/wattux/src/rust/wasm-bindgen/examples/webaudio)
Finished release [optimized] target(s) in 22.65s
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'internal error: entered unreachable code', crates/cli-support/src/decode.rs:157:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit code: 101
  full command: "/home/wattux/.cache/.wasm-pack/wasm-bindgen-814a8076c74d92e2/wasm-bindgen" "/home/wattux/src/rust/wasm-bindgen/target/wasm32-unknown-unknown/release/webaudio.wasm" "--out-dir" "/home/wattux/src/rust/wasm-bindgen/examples/webaudio/pkg" "--typescript" "--target" "bundler"
```

As far as we've observed, building does not work for anything that includes `web-sys`. Examples without it, eg `hello_world` work fine.. So this maybe just an issue on our side..

### Steps to Reproduce

Clone repo, navigate to `examples/webaudio/` and run either `wasm-pack build` or `npm run serve` (the latter uses the first, I assume).

### Expected Behavior

Example builds and runs just fine

### Actual Behavior

Building crashes at step `Installing wasm-bindgen...`

### Additional Context

wasm-pack: 0.9.1
rustc: 1.43.0
rustup: 1.21.1

Please let me know if you need the full backtrace or any additional informations. Thanks!

**Comment by alexcrichton** [comment] 2020-06-01 20:25
Thanks for the report! This is unfortunately, though, a duplicate of https://github.com/rustwasm/wasm-bindgen/issues/1227. For now to run the examples reliably you'll need to copy the example to a separate directory.

**Closed by alexcrichton** 2020-06-01 20:25 UTC
Labels: bug
