### ISSUE TITLE
Weak references fails to automatic garbage collect

### ISSUE THREAD

**Issue by yisibl** [rustwasm/wasm-bindgen#3903] opened 2024-03-26 13:55 UTC
### Summary

`wasm-bindgen` 2.9.1 has `--weak-refs` turned on by default, but I recompiled [resvg-js](https://github.com/yisibl/resvg-js/tree/main/wasm) to wasm to test it in Node.js and it still shows a constant increase in memory usage.

```js
  const pngData = resvg.render()
  const pngBuffer = pngData.asPng()
  // pngData.free() // I had to add `.free()` here to memory leak.
```

The documentation for wasm-bindgen says:

> Without weak references your JS integration may be susceptible to memory leaks in Rust, for example:
> You could forget to call .free() on a JS object, leaving the Rust memory allocated.

Please help me see what went wrong.

See https://github.com/yisibl/repro-resvg-wasm-memory-leak

**Comment by Liamolucko** [comment] 2024-03-27 01:37
This is a bug; somebody already noticed this and wrote a fix for it in #3743, but it never got finished.

We probably should've waited for this to be fixed before enabling weak references by default, but I'd forgotten about it... oops.

**Comment by yisibl** [comment] 2024-03-27 03:32
@Liamolucko There is another related issue [here](https://github.com/rustwasm/wasm-bindgen/issues/3854)

**Comment by mizdra** [comment] 2024-04-07 05:15
The cause of this memory leak is as described at https://github.com/yisibl/resvg-js/pull/318#issuecomment-2020979793. It contains both #3854 and #3917 issues.

I think I can close this issue in favor of the two issues.

What do you think? @yisibl

**Comment by daxpedda** [comment] 2024-04-18 21:04
Closing in favor of #3854.

**Closed by daxpedda** 2024-04-18 21:04 UTC
Labels: question
