### ISSUE TITLE
Depending on crates that use wasm-bindgen

### ISSUE THREAD

**Issue by OlofBlomqvist** [rustwasm/wasm-bindgen#3229] opened 2023-01-08 22:32 UTC
Hi! I have a crate that uses wasm_bindgen to expose a very limited number of methods to wasm.

My crate has a dependency that also uses wasm_bindgen and exports alot of methods which I do NOT want to expose when compiling my wasm file. Is it possible to skip processing wasm_bindgen marked items in the referenced crate so that my compiled wasm file only contain the methods I want to expose?

**Comment by daxpedda** [comment] 2023-12-30 09:27
Duplicate of #3759.

**Closed by daxpedda** 2023-12-30 09:27 UTC
Labels: question
