### ISSUE TITLE
#[wasm_bindgen(start)] occasionally causes webpack to error

### ISSUE THREAD

**Issue by liamcurry** [rustwasm/wasm-bindgen#1209] opened 2019-01-25 23:27 UTC
Using `#[wasm_bindgen(start)]` seems to occasionally cause Webpack to throw errors like this:

    ERROR in ./examples/counter_ecs/pkg/counter_ecs_bg.wasm
    Export "__wbindgen_start" with i64 as result can only be used for direct wasm to wasm dependencies
     @ ./examples/counter_ecs/pkg/counter_ecs.js 247:33-54 247:33-54
     @ ./examples/counter_ecs/static/index.js
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./examples/counter_ecs/static/index.js

    ERROR in ./examples/counter_ecs/pkg/counter_ecs_bg.wasm
    Export "main" with i64 as result can only be used for direct wasm to wasm dependencies
     @ ./examples/counter_ecs/pkg/counter_ecs.js 140:11-20 140:11-20
     @ ./examples/counter_ecs/static/index.js
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./examples/counter_ecs/static/index.js

Here is where that error appears in Webpack's source: https://github.com/webpack/webpack/search?q=%22wasm+to+wasm%22

I'm able to resolve this by just using `#[wasm_bindgen]` and running the `main` function manually.

There seems to be a few different things that trigger this error. Here is an example from the code I'm working on. If I compile this code with `yarn build` I see the error, but If I comment out these three lines it goes away:

https://github.com/sagan-software/oak/blob/da01f014be4a49eb7302d39921694367f503eca7/examples/counter_ecs/src/lib.rs#L82-L84

**Comment by alexcrichton** [comment] 2019-01-28 16:40
@xtuc hm I wonder if you could help take a look at this?

Checking out that latest commit, building it, and executing `wasm2wat` I get...

```wat
;; counter_ecs_bg.wasm
(module
  ;; ...
  (type (;15;) (func))
  ;; ...
  (import "./counter_ecs" "__wbindgen_defer_start" (func (;16;) (type 15)))
  ;; ...
  (func $main (type 15)
  ;; ...
    )
  ;; ...
  (start 16)
  ;; ...
  (export "main" (func $main))
  (export "__wbindgen_start" (func $main))
  ;; ...
  )
```

and 

```js
// counter_ecs.js
import * as wasm from './counter_ecs_bg';

// ...

export function __wbindgen_defer_start() {                
    Promise.resolve().then(() => wasm.__wbindgen_start());
}    

// ...                                               
```

I'm not sure where the i64 in the error message comes from because the function *should* have no types in the signature. Is this perhaps a bug in webpack's processing of wasm?

**Comment by alexcrichton** [comment] 2019-01-28 16:40
@liamcurry also, could you share your `package.json` and `package-lock.json` to see what versions of tools were in play?

**Comment by xtuc** [comment] 2019-01-28 16:46
Ok, I'll take a look at it. Based on your comment, is seems like a bug.

**Comment by xtuc** [comment] 2019-01-28 17:16
@liamcurry sorry I'm having trouble reproducing your issue. Could you please specify your Rust version, the branch you're on and how to launch the project?

**Comment by liamcurry** [comment] 2019-01-28 17:53
@alexcrichton I'm using `yarn` so I added my `yarn.lock` file, and `Cargo.lock` if that is helpful.

@xtuc Here are some versions, let me know if there's anything else you need:

```sh
$ rustc -V
rustc 1.33.0-nightly (19f8958f8 2019-01-23)

$ cargo -V
cargo 1.33.0-nightly (907c0febe 2019-01-20)

$ wasm-bindgen -V
wasm-bindgen 0.2.33

$ wasm-pack -V
wasm-pack 0.6.0
```

To launch the project:

```sh
git clone --single-branch --branch wasm-bindgen-error git@github.com:sagan-software/oak.git
cd oak
yarn install
yarn start
```

Then go to http://localhost:8080/counter_ecs/

**Comment by alexcrichton** [comment] 2019-02-01 16:13
@xtuc wanted to follow up, did you have a chance to reproduce this from the info @liamcurry gave?

**Comment by xtuc** [comment] 2019-02-04 21:53
Sorry for the delay here, I'll work on it asap.

**Comment by xtuc** [comment] 2019-02-08 17:58
@liamcurry i'm having trouble launching your example, i'm seeing:
```
    ERROR in ./examples/counter_ecs/static/index.js
    Module not found: Error: Can't resolve '../pkg/counter_ecs' in '/tmp/oak/examples/counter_ecs/static'
     @ ./examples/counter_ecs/static/index.js 1:0-28
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./examples/counter_ecs/static/index.js
````

**Comment by xtuc** [comment] 2019-02-08 18:14
OK! Finally got your error locally.

**Comment by alexcrichton** [comment] 2019-02-20 16:02
To follow up with this, @xtuc did this end up getting fixed in webpack?

**Comment by xtuc** [comment] 2019-02-20 16:30
@liamcurry it works with `webpack@4.29.5`.

**Comment by alexcrichton** [comment] 2019-02-20 16:42
Thanks @xtuc!

**Closed by alexcrichton** 2019-02-20 16:42 UTC
