### ISSUE TITLE
Is it possible to override the automatically generated typescript definition

### ISSUE THREAD

**Issue by GeorgeScrivener** [rustwasm/wasm-bindgen#1962] opened 2020-01-16 15:48 UTC
Is there any way to override the automatically generated typescript definitions?

I have the following problem:
```
// Rust definition:
pub fn render(context: web_sys::CanvasRenderingContext2d)

// Automatically generated typescript definition:
render(context: any): void;

// Signature I want:
render(context: CanvasRenderingContext2D): void;
```

I had a look at `typescript_custom_section` but that doesn't seem to do what I need.

What work would be required to improve the typescript generation for web_sys code?

This appears to be similar to issues #1847 & #1691

**Comment by alexcrichton** [comment] 2020-01-16 17:08
Thanks for the report! I think this is a duplicate of https://github.com/rustwasm/wasm-bindgen/issues/1691 so I'm gonna close in favor of that. Having the types for `web-sys` show up I think would unfortunately be pretty difficult, but may be worth pursuing as well!

**Closed by alexcrichton** 2020-01-16 17:08 UTC
Labels: question
