### ISSUE TITLE
What's the idiomatic way to type js closures in d.ts?

### ISSUE THREAD

**Issue by hillin** [rustwasm/wasm-bindgen#3628] opened 2023-09-21 02:27 UTC
E.g. in the example of [Receiving JavaScript Closures in Exported Rust Functions](https://rustwasm.github.io/wasm-bindgen/reference/receiving-js-closures-in-rust.html#receiving-javascript-closures-in-exported-rust-functions):

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct VecU32 {
    xs: Vec<u32>,
}

#[wasm_bindgen]
impl VecU32 {
    pub fn each(&self, f: &js_sys::Function) {
        let this = JsValue::null();
        for &x in &self.xs {
            let x = JsValue::from(x);
            let _ = f.call1(&this, &x);
        }
    }
}
```

I'd like to type the `f` parameter of the `each` function in the d.ts file, supposedly like this:

```typescript
each(f: (value: number) => void);
```

**Comment by daxpedda** [comment] 2023-09-21 06:46
This is currently not supported.

Duplicate of https://github.com/rustwasm/wasm-bindgen/issues/3107.

**Closed by daxpedda** 2023-09-21 06:46 UTC
Labels: question

**Comment by Liamolucko** [comment] 2023-09-21 07:46
> This is currently not supported.

Yes it is, you can make a custom subclass of `js_sys::Function` and give it the appropriate `typescript_type`:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(extends = js_sys::Function, typescript_type = "(value: number) => void")]
    pub type NumberFunc;
}

#[wasm_bindgen]
pub struct VecU32 {
    xs: Vec<u32>,
}

#[wasm_bindgen]
impl VecU32 {
    pub fn each(&self, f: &NumberFunc) {
        let this = JsValue::null();
        for &x in &self.xs {
            let x = JsValue::from(x);
            let _ = f.call1(&this, &x);
        }
    }
}
```

The same solution works for #3107. (Well, not perfectly, the OP there asked for an attribute on the function rather than having to declare a type, but more or less.)
