### ISSUE TITLE
Enum type exported to TypeScript, but not used in params

### ISSUE THREAD

**Issue by benma** [rustwasm/wasm-bindgen#3505] opened 2023-07-05 09:08 UTC
### Describe the Bug

```rust
#[wasm_bindgen]
pub enum Foo {
    A = 1,
    B = 2,
}

#[wasm_bindgen]
pub async fn foo(foo: Foo) -> Result<(), ()> {
   // ... 
}
```

Produces this TypeScript:

```
export enum Foo {
  A = 1,
  B = 2,
}
export function foo(foo: number): void
```

### Expected Behavior

I expected the function to be exported as:

```
export function foo(foo: Foo): void
```

**Comment by Stefan-Hanke** [comment] 2023-07-06 05:09
Looks like a duplicate to https://github.com/rustwasm/wasm-bindgen/issues/2154

**Comment by daxpedda** [comment] 2023-07-06 09:12
Duplicate of #2154.

**Closed by daxpedda** 2023-07-06 09:12 UTC
Labels: bug
