### ISSUE TITLE
KeyboardEvent::key() and code() don't work in wasm-bindgen 0.2.41 in Firefox

### ISSUE THREAD

**Issue by nstoddard** [rustwasm/wasm-bindgen#1436] opened 2019-04-11 04:32 UTC
### Describe the Bug

In wasm-bindgen 0.2.41, `KeyboardEvent::key()` and `::code()` always return the empty string. In 0.2.40 they worked fine. I'm not sure whether this bug is in wasm-bindgen, web-sys, or another related crate.

### Steps to Reproduce

1. Compile and run https://github.com/nstoddard/webgl-gui-demo
2. Press one of the arrow keys

### Expected Behavior

The arrow keys should move the diamond in the middle.

### Actual Behavior

The arrow keys do nothing. If logging of `pressed_keys` is added to `Demo::handle_pressed_keys`, it shows that the keys are always empty strings (they should be "ArrowLeft" or similar).

### Additional Context

I can only repro this in Firefox, not Chrome. I'm using Linux; I don't know if it happens on other platforms.

If you downgrade the wasm-bindgen dependency to 0.2.40 (which also requires downgrading some dependencies in [webgl-wrapper](https://github.com/nstoddard/webgl-wrapper) and [webgl-gui](https://github.com/nstoddard/webgl-gui)) the arrow keys work.

**Comment by alexcrichton** [comment] 2019-04-11 14:27
Thanks for the report! Looks like this is an accidental regression from https://github.com/rustwasm/wasm-bindgen/pull/1414 (cc @RReverser ) which shoudl be fixed in https://github.com/rustwasm/wasm-bindgen/pull/1442

**Closed** 2019-04-11 14:34 UTC
Labels: bug
