### ISSUE TITLE
Consider using `unsafe` instead of `--cfg` for unstable features

### ISSUE THREAD

**Issue by ctron** [rustwasm/wasm-bindgen#2339] opened 2020-10-26 11:45 UTC
### Motivation

Currently it is not possible to access a web browsers clipboard in a sane way. The Clipboard API is unstable and thus not available by default, while the `Document.executeCommand` call is no longer present.

I do understand to put in additional safeguard on unstable APIs, however requiring the user to add ad `--cfg` option to RUSTC_FLAGS seems rather drastic.

The problem with that is, that you cannot abstract and fix the issue in a library, because the final application developer must enable this flag.

### Proposed Solution

If APIs that are consider unstable would be marked (Rust) `unsafe`, then that would add some extra safeguards as well. However, a library could go ahead and take care of this situation.

Similar to other cases, where implementors, using `unsafe` functionality guarantee safe functionality.

**Comment by ctron** [comment] 2020-10-28 16:51
As I tried to explain, I understand the reason for gating. I am only looking for a reasonable way to work with this.

I understand that this situation here isn't about memory safety, but about API stability. However, the way this is currently enforced, doesn't allow a library to cover this. Using `unsafe` would.

**Comment by alexcrichton** [comment] 2020-10-29 15:44
Sorry but that's the goal of the system. The difficulty using these APIs is considered a feature, not a bug. The intention is that using these APIs is an application-level decision, not a library-level decision. I feel there's not much more that can be done while the APIs are unstable.

**Comment by Follpvosten** [comment] 2021-04-27 11:55
While I get why these APIs are hidden, it would still be nice to make them usable with a bit less of a hassle. I'm not building a library, but a webapp, and from my point of view it would be great if this could be a feature instead of a cfg flag.
For example, chrono also hides unstable APIs behind an `unstable-x` feature and I think this would be a good way to still turn them off by default so the user has to make a conscious decision in enabling them, but at the same time making it less of a hard wall if someone needs to use them. (For example, I have no idea how I would pass rustflags to rust-analyzer to make this work for me right now. It would be great if it was *a little bit* easier.)

**Comment by arctic-hen7** [comment] 2021-12-24 04:47
Maybe I'm barking up the wrong tree, but #2684 mentions that you can use unstable APIs reasonably conveniently by adding the following to `.cargo/config.toml` (within your project):

```toml
[build]
rustflags = ["--cfg=web_sys_unstable_apis"]
```

For me at least, this seems to work very well with IDE integration (Emacs) and normal `cargo build` commands.

**Comment by ShafSpecs** [comment] 2023-02-23 08:51
@Follpvosten For using unstable apis with `rust-analyzer`, add this to your vscode settings.json:
```json
"rust-analyzer.runnableEnv": {
    "RUSTFLAGS": "--cfg=web_sys_unstable_apis"
 }
```
and then  restart your extensions host. It should now work with the unstable apis, saved my life and brain cells ngl.

*P.S. Don't forget to enable it in your `config.toml` too*

**Comment by MartinKavik** [comment] 2024-06-04 14:08
`rust-analyzer` config update: `"rust-analyzer.runnableEnv"` is now _"Unknown Configuration Setting"_, but this one seems to work:
```json
"rust-analyzer.cargo.extraEnv": {
    "RUSTFLAGS": "--cfg=web_sys_unstable_apis"
}
```

**Comment by daxpedda** [comment] 2024-06-27 09:50
I'm gonna go ahead and close this, seeing that we don't plan to move to `unsafe` for unstable features.

**Closed** 2024-06-27 09:50 UTC
Labels: enhancement
