### ISSUE TITLE
The hello world example doesn't build

### ISSUE THREAD

**Issue by P-E-Meunier** [rustwasm/wasm-bindgen#197] opened 2018-05-14 16:33 UTC
I get the following error on a clone of this repository, when running `build.rs` in `examples/hello_world`:

```
ERROR in ./hello_world_bg.wasm
Module not found: Error: Can't resolve 'env' in '/home/pe/Recherche/origami/designer-rs/wasm-bindgen/examples/hello_world'
 @ ./hello_world_bg.wasm
 @ ./hello_world.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8082 ./index.js
ℹ ｢wdm｣: Failed to compile.
```

I'm using the latest Rust nightly.

**Comment by alexcrichton** [comment] 2018-05-14 21:34
@P-E-Meunier hm I just exected this locally and it seems to have worked. Can you gist the full error you were seeing as well as the `package-lock.json` perhaps?

**Comment by P-E-Meunier** [comment] 2018-05-15 06:41
Full error: https://gist.github.com/P-E-Meunier/f820c9dcfda1cb90bb7f05a30dcc1bce
Lock: https://gist.github.com/P-E-Meunier/cba87546d8b35a4021340c93e37faef1

**Comment by P-E-Meunier** [comment] 2018-05-15 07:06
Wait, the `add` examples builds fine, with the same configuration.

**Comment by xtuc** [comment] 2018-05-16 12:47
I'm not able to reproduce it. It's probably something on your side @P-E-Meunier.

**Comment by P-E-Meunier** [comment] 2018-05-16 12:55
I'm a little surprised that cargo + npm/yarn are not able to make this reproducible. I'll try in a clean virtual machine with a more standard system and report back here to see where the differences are.

**Comment by xtuc** [comment] 2018-05-16 12:57
Could you please share your hello_world_bg.wasm?

**Comment by xtuc** [comment] 2018-05-16 20:19
Did you modify the example? The issue is that you have an `env` module in the imports.

I have:
```
  (import "./hello_world" "__wbg_f_alert_alert_n" (func $__wbg_f_alert_alert_n (param i32) (param i32)))
  (import "./hello_world" "__wbindgen_throw" (func $__wbindgen_throw (param i32) (param i32)))
```

Do you have an idea @alexcrichton?

**Comment by P-E-Meunier** [comment] 2018-05-16 21:03
Yes, according to `rustc --version`, I do have the latest nightly.
However, I'm using a nonstandard setup: I get my binaries from the rustup server, but not using rustup (using NixOS instead).

It seems there's something wrong with the installer. What part of the toolchain can cause this? Where should I look if I wanted to fix this?

**Comment by alexcrichton** [comment] 2018-05-16 22:35
The Rust compile rewrites imports after LLD has executed to fix the module that items are imported from, so if you're using the official binaries I'm not sure how this error would come up :(

It does sound like a local toolchain isssue, though, I'm just not sure how!

**Comment by alexcrichton** [comment] 2018-05-21 22:43
I'm gonna close this for now as it seemed like this was a local toolchain issue, but if it turns out to be a wasm-bindgen issue please let me know!

**Closed by alexcrichton** 2018-05-21 22:43 UTC

**Comment by David-OConnor** [comment] 2018-07-16 22:53
Same issue. I'll post most info if I can narrow it down.

**Comment by alexcrichton** [comment] 2018-07-16 23:48
@David-OConnor oh dear sounds bad! If you've got a reproduction feel free to file a new issue at any time!

**Comment by sciyoshi** [comment] 2018-08-01 06:01
Looks like the info here could be relevant: https://github.com/rust-lang-nursery/rand/issues/478#issuecomment-392371963
