### ISSUE TITLE
Execute the `wasm-pack test --node` command, in fact, it does not call the start function annotated with #[wasm_bindgen(start)].

### ISSUE THREAD

**Issue by baoyachi** [rustwasm/wasm-bindgen#3739] opened 2023-12-08 02:32 UTC
The following are the dependencies of my project.  When I execute the `wasm-pack test --node` command, in fact, it does not call the`start` function annotated with `#[wasm_bindgen(start)]`.

```diff
pub static GLOBAL_DATA: OnceCell<Mutex<Vec<VerboseLog>>> = OnceCell::new();

#[wasm_bindgen(start)]
+ fn start() {
    GLOBAL_DATA.get_or_init(|| {
        let t = Default::default();
        init_with_level(Level::Trace).unwrap();
        t
    });
}
...
```

```bash
~  wasm-pack --version
wasm-pack 0.12.1

```

```toml
[dependencies]
serde-wasm-bindgen = "0.5"
serde_json = "1.0.108"
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

```

**Comment by Liamolucko** [comment] 2023-12-08 09:59
This seems to have been an intentional choice at some point, since it's explicitly disabled in `wasm-bindgen-test-runner`:

https://github.com/rustwasm/wasm-bindgen/blob/cfe3dc28a101a1b4cf7ab7ca6db358eadc7a4063/crates/cli/src/bin/wasm-bindgen-test-runner/main.rs#L193

I think it's probably because `#[wasm_bindgen(start)]` was intended to be used like `fn main()`, rather than for initialising global state like how you're using it, and you don't want your `main` function to be run during tests.

I don't have any opinion on what the 'correct' way to use it is, but I'm worried that enabling `#[wasm_bindgen(start)]` in tests might end up breaking other people's tests, which are relying on it not being run.

**Comment by hamza1311** [comment] 2023-12-08 11:57
`#[wasm_bindgen(start/main)]` is effectively the same as `fn main()` so I don't think it should be called from tests. 

I would put the init logic for tests in a function that is called before each test. Unfortunately, Rust doesn't give us a `before_each` hook so it has to called manually.

**Comment by daxpedda** [comment] 2023-12-08 12:12
Considering all maintainers are against it I'm going to go ahead and close this.

**Closed by daxpedda** 2023-12-08 12:12 UTC
Labels: breaking-change

**Comment by baoyachi** [comment] 2023-12-11 01:16
So sad. 😭
