### ISSUE TITLE
rust nightly errors with doesn't have an adapter listed

### ISSUE THREAD

**Issue by ctaggart** [rustwasm/wasm-bindgen#1929] opened 2019-12-23 07:56 UTC
With rust nightly, I'm getting one of these two errors:
```
error: import of `__wbg_cargowebsnippetc26ddf75f581148e029dfcd95c037bb50d502e43_f494f4a63cf92998` doesn't have an adapter listed
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit code: 1

error: import of `__wbg_cargowebsnippetc26ddf75f581148e029dfcd95c037bb50d502e43_f494f4a63cf92998` doesn't have an import map item listed
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit code: 1
```

I'm building with `wasm-pack build --target web`.

```
$ cargo install-update --list
Package           Installed  Latest    Needs update
wasm-bindgen-cli  v0.2.56    v0.2.56   No
wasm-pack         v0.8.1     v0.8.1    No
```

rustup default nightly
nightly-x86_64-apple-darwin unchanged - rustc 1.42.0-nightly (9b98af84c 2019-12-22)

It is working fine on rust stable.

**Comment by trivigy** [comment] 2020-01-04 06:03
Same exact error here. Seems that even the hashes match up. Would greatly appreciate some recommendation on how to debug this. I am on a slightly newer nightly version. `rustc 1.42.0-nightly (3a3f4a7cb 2019-12-28)`
```
error: import of `__wbg_cargowebsnippetc26ddf75f581148e029dfcd95c037bb50d502e43_f494f4a63cf92998` doesn't have an adapter listed
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit code: 1
```

**Comment by alexcrichton** [comment] 2020-01-06 17:27
Thanks for the report! The bad news is that this was a breakage caused by a behavior change in upstream Rust, but the good news is that our internal test suite caught it and I just was on break and wasn't around to fix it! I've posted a fix for this at https://github.com/rustwasm/wasm-bindgen/pull/1942

**Closed** 2020-01-06 17:44 UTC
Labels: bug

**Comment by ctaggart** [comment] 2020-01-06 17:52
Hope you had a wonderful break! Thanks for the fix. I really like wasm-bindgen.

**Comment by t-moe** [comment] 2024-06-25 12:33
Without having a full reproducer at hand, my colleague observed 
`error: import of __wbindgen_array_new doesn't have an adapter listed` 
 today when running wasm-bindgen on his mac... 

he was also using rust nightly and a command like `wasm-pack build --target browser --mode normal --no-typescript`

anybody else?
