### ISSUE TITLE
[...] `/path/to/project/root/package.json` can currently [..] have [...] no other fields

### ISSUE THREAD

**Issue by pablosichert** [rustwasm/wasm-bindgen#1921] opened 2019-12-19 21:19 UTC
Hey there!

I have a project directory, where both `cargo` and `npm` reside. The `package.json` has, among others, a `scripts` section to centralize custom commands related to the project.

When I add

```rust
#[wasm_bindgen(module = "/src/foo.ts")]
[...]
```

to a Rust file, I get the following error when compiling (in this case by invoking `wasm-pack`, but it should be unrelated):

```
error: NPM manifest found at `/path/to/project/root/package.json` can currently only have one key, `dependencies`, and no other fields
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit code: 1
```

Can you help me understand why this limitation exists? Why is e.g. ignoring the other keys not an option?

**Comment by adam-cyclones** [comment] 2019-12-27 10:23
I am also having the same issue (I am also in a ts project)

I changed my import to point to some JS incase it was that. 
```
#[wasm_bindgen(module = "lib-jess/src/bindings/ts/helpers/import.js")]
extern "C" {
    fn import_jess_sync(path: &str) -> Result<String, JsValue>;
}
```

**Comment by pratyushj** [comment] 2019-12-27 12:28
I was using JS and had the same error. Had to move all the JS code to a separate folder and it worked :grimacing:

**Comment by adam-cyclones** [comment] 2019-12-27 23:24
Interesting il try that. I think the function I wanted to export was in the same folder as some ts sources. This looks like an edge case and some unexpected behaviour, certainly unhelpful error either way.

**Comment by alexcrichton** [comment] 2020-01-06 15:21
Thanks for the report! This was initially done to be as conservative as possible, but I think that this has tripped up enough users that it's fine to ignore all non-`dependencies` keys and only use the ones that are relevant. In that sense I'd be happy to have a PR to change this!

**Comment by adam-cyclones** [comment] 2020-01-14 15:00
@alexcrichton its this code at `crates/cli-support/src/js/mod.rs:2776`

``` rust
if key != "dependencies" || iter.next().is_some() {
            bail!(
                "NPM manifest found at `{}` can currently only have one key, \
                 `dependencies`, and no other fields",
                path.display()
            );
}
```

My Wasm module is cohabiting with a Typescript package, so I did what most would do, `npm init`, this means I share this package with several other libraries and test tools. I understand the philosophy of pay for only what you use and minimalism but, the package.json should be out of scope, it is not in Rusts domain. I would trust npm do its validating checks. Unless I am missing something critical I don't understand this check at all, what happens if I just delete it?

Happy to PR this, just not contributed to anything before.

**Comment by alexcrichton** [comment] 2020-01-15 16:46
@adam-cyclones yep that sounds like the right spot, and it should likely be pretty safe to just delete.

**Closed** 2020-01-21 19:04 UTC
Labels: question

**Comment by adam-cyclones** [comment] 2020-01-21 19:25
Sorry I started a new job, have been preoccupied. Glad it's closed 😁
