### ISSUE TITLE
Upgrading from 0.2.93 to 0.2.95 appears to newly build wasm modules with multiple tables, breaking wasm2js

### ISSUE THREAD

**Issue by fishface60** [rustwasm/wasm-bindgen#4234] opened 2024-10-29 13:52 UTC
### Describe the Bug

When using 0.2.95 the wasm builds differently to 0.2.93.

```
wasm2js -o bundle/src/mt_gurps_bg.wasm.js pkg/mt_gurps_bg.wasm
Fatal: error: modules with multiple tables are not supported yet.
```

This works in 0.2.93. I assume something changed that causes the emitted wasm to be different enough that wasm2js can no longer handle it.

This may be fixed in a newer version of binaryen, but Ubuntu 24.04 LTS and Debian stable are on 108-1

### Steps to Reproduce

1. Clone https://gitlab.com/richardmaw/mt-gurps
2. Change the wasm-bindgen dependency in `crates/mt_gurps/Cargo.toml` to 0.2.95
3. Observe the error displayed above

See https://gitlab.com/richardmaw/mt-gurps/-/jobs/8215439401 for a CI run with the failure.

### Expected Behavior

Allowing wasm-bindgen to continues to work with a stable released version of binaryen.

### Actual Behavior

It somehow produces incompatible wasm.

**Comment by fishface60** [comment] 2024-10-29 14:09
If a newer binaryen fixes this I'm happy for the issue to be closed and I'll wait for a distro stable release with the new version before updating wasm-bindgen.

**Comment by daxpedda** [comment] 2024-11-07 18:41
I believe that this is related to the reference types proposal being enabled by default in Rust v1.82, which causes `wasm-bindgen` to apply its reference type transformations as well, which introduces multiple tables.

Let me know if I'm wrong about that.

Duplicate of #4211.

**Closed by daxpedda** 2024-11-07 18:41 UTC
Labels: bug
