### ISSUE TITLE
getting the error "'internal error: entered unreachable code', crates/cli-support/src/decode.rs:74:18" when js_sys crate tests execution

### ISSUE THREAD

**Issue by davnav** [rustwasm/wasm-bindgen#1886] opened 2019-11-30 00:57 UTC
### Describe the Bug
I was trying to execute the js_sys crate tests (**wasm_bindgen/crates/js-sys/tests** )using command: **wasm-pack test  --headless --chrome**

But getting below error : _thread 'main' panicked at 'internal error: entered unreachable code', crates/cli-support/src/decode.rs:74:18_

**headless.rs**: I added one line  statement in  headless.rs file 
use wasm_bindgen_test::*;  as it was not detecting **wasm_bindgen_test** crate

attached full file below:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=43e56667ab9b7ac75b416a3fe6d44b2c

**Cargo.toml :**
attached full file below: ( I think I did not change anything in this file )
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5b2edbbf88e85e6a67e98bd02dc0a423

When I run the tests in js-sys folder using below command: 
**wasm-pack test  --headless --chrome** , I am getting error.

### Steps to Reproduce

1. download wasm-bindgen using git clone and go to the folder wasm-bindgen/crates/js-sys/tests
2. Click on 'edit the headless.rs to add   use wasm-bindgen-test::* '  and save
3.Go to the directory  js-sys . and run below command
4.wasm-pack test  --headless --chrome
5. See error
_thread 'main' panicked at 'internal error: entered unreachable code', crates/cli-support/src/decode.rs:74:18
stack backtrace:
   0:           0x80eae4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h45d79e0e31af34d1
   1:           0x84c08c - core::fmt::write::h6412e51ee7d5337d
   2:           0x808fe7 - std::io::Write::write_fmt::hc321dd9edd55d777
   3:           0x8115c5 - std::panicking::default_hook::{{closure}}::h0556362794d99987
   4:           0x8112b6 - std::panicking::default_hook::h9a006f22406ae1a5
   5:           0x811cc5 - std::panicking::rust_panic_with_hook::h00181808d6f69bb1
   6:           0x6c2d95 - std::panicking::begin_panic::ha439e1509c854216
   7:           0x713097 - <wasm_bindgen_cli_support::decode::Program as wasm_bindgen_cli_support::decode::Decode>::decode::h397b709ba27c137b
   8:           0x6f7873 - wasm_bindgen_cli_support::webidl::process::h760e5f6095768351
   9:           0x6cc5ba - wasm_bindgen_cli_support::Bindgen::generate_output::hbc7c9023771a047d
  10:           0x41895e - wasm_bindgen_cli_support::Bindgen::generate::hfa138323617ba83c
  11:           0x44ae23 - wasm_bindgen_test_runner::main::hc872a42ac72dca24
  12:           0x444137 - std::rt::lang_start::{{closure}}::hfc07cb990812863c
  13:           0x8116f3 - std::panicking::try::do_call::h82a5bff94f1b8fce
  14:           0x81a0da - __rust_maybe_catch_panic
  15:           0x81211b - std::rt::lang_start_internal::h30062e1a2e0b8896
  16:           0x44bc02 - main
error: test failed, to rerun pass '--test headless'
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit code: 101_

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).
https://github.com/rustwasm/wasm-bindgen/tree/master/crates/js-sys/tests

### Expected Behavior

I thought  that would run the test cases in headless.rs file.

### Actual Behavior

error as below:
thread 'main' panicked at 'internal error: entered unreachable code', crates/cli-support/src/decode.rs:74:18
stack backtrace:

[https://imgur.com/9kdeFg0](https://imgur.com/9kdeFg0.png)

**Comment by alexcrichton** [comment] 2019-12-02 15:51
Thanks for the report!

This is unfortunately a duplicate of https://github.com/rustwasm/wasm-bindgen/issues/1227, although not easy to know that! I'm going to close this in favor of that.

**Closed by alexcrichton** 2019-12-02 15:51 UTC
Labels: bug
