### ISSUE TITLE
web-sys examples broken since 0.2.81

### ISSUE THREAD

**Issue by jhinch** [rustwasm/wasm-bindgen#2963] opened 2022-06-24 07:38 UTC
### Describe the Bug

It appears as though all of the live web-sys examples in the wasm-bindgen guide are not working and confirmed they were not working when running locally as well. Examples tested which are not working:

* https://rustwasm.github.io/wasm-bindgen/examples/dom.html
* https://rustwasm.github.io/wasm-bindgen/examples/paint.html
* https://rustwasm.github.io/wasm-bindgen/examples/todomvc.html

It seems like other live examples are still working such as the hello_world example

* https://rustwasm.github.io/wasm-bindgen/exbuild/hello_world/

### Steps to Reproduce

1. Checkout main of wasm-bindgen
2. `cd examples/dom`
3. `npm install`
4. `npm run serve`
5. Open http://localhost:8080 in your browser
6. See that 'Hello rust!' is never appended to the page

### Expected Behavior

examples/dom is expected to append a <p> tag with the text `hello rust!`

### Actual Behavior

Nothing happens

### Additional Context

I ran a git bisect between 0.2.80 and the tip of main and it found 062aa5f70a1e8a170d0ae90123ebdeb3242ac782 as the first bad commit

**Comment by Liamolucko** [comment] 2022-07-08 11:05
I think this was caused by #2961, so it should be fixed now.

**Comment by gengjiawen** [comment] 2022-07-20 15:15
@Liamolucko Is there any plan to draft a new release ?

**Comment by Liamolucko** [comment] 2022-07-25 23:17
> @Liamolucko Is there any plan to draft a new release ?

0.2.82 was just released (in #3002)

**Closed** 2022-08-15 08:27 UTC
Labels: bug
