### ISSUE TITLE
ReadableStreamReadResult methods wrong?

### ISSUE THREAD

**Issue by andrewbaxter** [rustwasm/wasm-bindgen#3553] opened 2023-08-10 12:14 UTC
### Describe the Bug

https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.ReadableStreamReadResult.html

I think `done` and `value` should return bool/jsvalue rather than take them as parameters.

I'm not 100% sure about conventions, but AFAICT this is a result of a `read()` call for extracting data so would never be constructed by hand. https://stackoverflow.com/questions/75141183/how-to-select-a-file-as-bytes-or-text-in-rust-wasm cites having an issue with it.  https://github.com/MattiasBuelens/wasm-streams/blob/main/src/readable/sys.rs#L176 shows what I expected the interface to be.

I didn't see an existing issue so I'm opening this for clarity.

**Comment by daxpedda** [comment] 2023-08-11 15:21
Duplicate of #1793.
See #2782 as well.

**Closed by daxpedda** 2023-08-11 15:21 UTC
Labels: bug
