### ISSUE TITLE
Anchor tag does not contain href property

### ISSUE THREAD

**Issue by jesskfullwood** [rustwasm/wasm-bindgen#1315] opened 2019-03-05 19:10 UTC
The `href` attribute is inherited by the `<a>` tag via `HTMLHyperlinkElementUtils` as per
[here](https://github.com/rustwasm/wasm-bindgen/blob/f161717afefd87d1cfea9ce830d055186169a70f/crates/web-sys/webidls/enabled/HTMLAnchorElement.webidl#L38). However for the life of me I can't find the `href` getter anywhere in the docs, nor any mention of `HTMLHyperlinkElementUtils`. `href` is of course the most useful property of `<a>`.

**Comment by alexcrichton** [comment] 2019-03-05 22:19
Thanks for the report! Looking into this I believe it's a duplicate of https://github.com/rustwasm/wasm-bindgen/issues/893, and `HTMLHyperlinkElementUtils` is indeed on that list. 

We may be able to fix this issue specifically though by manually removing the attribute perhaps and/or switching it to a `partial interface`? The best fix though is to probably just fix the codegen for webidl to not fully ignore these tags!

**Closed** 2019-04-15 17:36 UTC
Labels: web-sys

**Comment by marienz** [comment] 2019-06-17 04:16
Although web-sys now generates bindings for HTMLHyperlinkElementUtils, I still cannot figure out how to actually use them. Calling `a.dyn_ref::<HTMLHyperlinkElementUtils>()` on an `HTMLAnchorElement` fails, and the methods from `HTMLHyperlinkElementUtils` are not present on `HTMLAnchorElement`.

https://html.spec.whatwg.org/multipage/semantics.html#htmlhyperlinkelementutils (which 
HTMLHyperlinkElementUtils.webidl links to as its origin) has `interface mixin HTMLHyperlinkElementUtils`. `mixin` is missing from the `HTMLHyperlinkElementUtils.webidl` in web-sys. I tried adding `mixin` and that seems to work: it adds a working `set_href` to `HTMLAnchorElement`.

Is this a problem with the .webidl file, or am I overlooking a different way of using `HTMLHyperlinkElementUtils`?

**Comment by alexcrichton** [comment] 2019-06-17 12:34
This is probably a case where we can just edit the webidl directly, especially if it's officially included upstream!

@marienz mind sending a PR?
