### ISSUE TITLE
Can `Promise::new` argument be narrowed from `FnMut` to `FnOnce`?

### ISSUE THREAD

**Issue by mwberry** [rustwasm/wasm-bindgen#3550] opened 2023-08-08 05:54 UTC
### Summary

I was attempting to capture a variable into a closure and was getting nagged by the borrow checker. Once I dug into it, I noticed that `Promise::new` takes an argument of `FnMut`. [If I'm reading the MDN documentation right,](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise#parameters) the "executor" passed to `Promise::new` will only be executed once, so an `FnMut` is a bit overkill. On the rust side, making this an `FnOnce` will make it easier to capture variables into the closure without having to worry about ownership.

### Additional Details

[Original commit that adds `Promise`](https://github.com/rustwasm/wasm-bindgen/commit/eee71de0ce9e563403d51eebc3c2b5dfe4a11d54#diff-1178cf994c14d2170f16630651bd7800406f8d5a9a644f290214674e2b8a94adR3067). It's been largely untouched since then, other than adding the `dyn` keyword.

Example using [the current `FnMut` interface](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cad807629d15a905f6cfdd7bbe875162)

```
fn main() {
    let sender = Sender{};
    let mut sender: Option<Sender> = Some(sender);
    let mut executor : Box<dyn FnMut(Function, Function)> = Box::new(move |accept, reject| {
        if sender.is_none() { panic!("Called twice"); }
        let mut sender: Option<Sender> = sender.take();
        let window = Window{};
        let on_timeout : Box<dyn FnMut()> = Box::new(move || {
            if sender.is_none() { panic!("Called twice"); }
            let sender: Sender = sender.take().unwrap();
            sender.send();
        });
        let on_timeout : Closure<dyn FnMut()> = Closure::new(on_timeout);
        window.set_timeout_with_callback_and_timeout_and_arguments(on_timeout.unchecked_ref(), 100, &Array{}).unwrap();
    });
    Promise::new(&mut executor);
}
```

Compare to [the alternative using the `FnOnce` Interface](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0a30d92a667d54f049a61cdd02a2654a).

```
fn main() {
    let sender = Sender{};
    
    let mut executor : Box<dyn FnOnce(Function, Function)> = Box::new(move |accept, reject| {
        
        
        let window = Window{};
        let on_timeout : Box<dyn FnOnce()> = Box::new(move || {
            
            
            sender.send();
        });
        let on_timeout : Closure<dyn FnOnce()> = Closure::new(on_timeout);
        window.set_timeout_with_callback_and_timeout_and_arguments(on_timeout.unchecked_ref(), 100, &Array{}).unwrap();
    });
    Promise::new(&mut executor);
}
```

**Comment by daxpedda** [comment] 2023-08-08 08:53
Duplicate of https://github.com/rustwasm/wasm-bindgen/issues/1763.

**Closed by daxpedda** 2023-08-08 08:53 UTC
Labels: question
