### ISSUE TITLE
How to call function on an object?

### ISSUE THREAD

**Issue by dakom** [rustwasm/wasm-bindgen#1428] opened 2019-04-07 21:14 UTC
### Summary

Given a `js_sys::Object`, how do you call one of its functions?

### Additional Details

Specifically I get a webgl extension via https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGlRenderingContext.html#method.get_extension

After extracting the inner object, I want to call its functions from Rust (e.g. https://developer.mozilla.org/en-US/docs/Web/API/ANGLE_instanced_arrays#Methods)

How do I do this? :)

**Comment by Pauan** [comment] 2019-04-08 03:31
@dakom You can use `Reflect::get` to access the members and then `Reflect::apply` to call them.

But that's pretty terrible (and slow), so a much better approach is to create some bindings for it:

```rust
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_name = ANGLEInstancedArrays)]
    type AngleInstancedArrays;

    #[wasm_bindgen(method, getter, js_name = VERTEX_ATTRIB_ARRAY_DIVISOR_ANGLE)]
    fn vertex_attrib_array_divisor_angle(this: &AngleInstancedArrays) -> i32;

    #[wasm_bindgen(method, catch, js_name = drawArraysInstancedANGLE)]
    fn draw_arrays_instanced_angle(this: &AngleInstancedArrays, mode: u32, first: i32, count: i32, primcount: i32) -> Result<(), JsValue>;

    // TODO offset should be i64
    #[wasm_bindgen(method, catch, js_name = drawElementsInstancedANGLE)]
    fn draw_elements_instanced_angle(this: &AngleInstancedArrays, mode: u32, count: i32, type_: u32, offset: i32, primcount: i32) -> Result<(), JsValue>;

    #[wasm_bindgen(method, js_name = vertexAttribDivisorANGLE)]
    fn vertex_attrib_divisor_angle(this: &AngleInstancedArrays, index: u32, divisor: u32);
}
```

Then you can convert your `Object` into an `AngleInstancedArrays` by using this:

```rust
let foo = foo.unchecked_into::<AngleInstancedArrays>();
```

----

@alexcrichton @fitzgen Can we somehow auto-generate bindings for the WebGL extensions? There is [IDL for it](https://www.khronos.org/registry/webgl/extensions/).

**Comment by alexcrichton** [comment] 2019-04-08 14:47
I think this is a duplicate of https://github.com/rustwasm/wasm-bindgen/issues/1257, so I'm going to close in favor of that (but cc @Pauan's excellent answer over there) and the general problem for supporting this is tracked at https://github.com/rustwasm/wasm-bindgen/issues/893 which I think https://github.com/rustwasm/wasm-bindgen/pull/1405 may help start paving the path towards implementing.

**Closed by alexcrichton** 2019-04-08 14:47 UTC
Labels: question

**Comment by dakom** [comment] 2019-04-14 15:44
> #[wasm_bindgen(js_name = ANGLEInstancedArrays)]
    type AngleInstancedArrays;

@Pauan Can you please explain a little more what's going on there?

The section from The Rust Book that talks about [type aliases](https://doc.rust-lang.org/beta/book/ch19-04-advanced-types.html#creating-type-synonyms-with-type-aliases
) doesn't seem to mention creating a type alias to nothing...

e.g. all the examples there have `type foo = bar` and I'm not clear on what's happening with just `type foo`

Sorry for another newbie question... and I realize this might not be specific to wasm-bindgen, but I'm thinking maybe the annotation above it is doing some magic?

**Comment by Pauan** [comment] 2019-04-14 17:35
@dakom It's not a type alias, it's an extern type (it's inside of an `extern` block).

It's something [specific to wasm-bindgen](https://rustwasm.github.io/docs/wasm-bindgen/reference/types/imported-js-types.html), it's not used in Rust in general.

It basically says "create a new type in Rust, but it's actually a JS type, so internally it just uses `JsValue`".

It's basically just used to create statically type safe Rust types as representations of JS types.

**Comment by WolfieWerewolf** [comment] 2019-04-22 22:09
@Pauan I just wanted to thank you for the above information... Using your documentation I was able to achieve the following (maybe this helps someone else)...

```rust
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_name = EXT_texture_filter_anisotropic)]
    type ExtTextureFilterAnisotropic;
}
```

```rust
let mut extension = ctx.gl.get_extension("EXT_texture_filter_anisotropic").unwrap().unwrap()
            .unchecked_into::<ExtTextureFilterAnisotropic>();

        let property = JsValue::from_str("MAX_TEXTURE_MAX_ANISOTROPY_EXT");
        let value = js_sys::Reflect::get(&extension, &property);


        console::log_1(&extension);
        console::log_1(&property);
        console::log_1(&value.unwrap());

```

![image](https://user-images.githubusercontent.com/10762757/56535327-db62d100-6531-11e9-917f-0c81138d6fdb.png)
@alexcrichton The team has done a tremendous job of the WASM bind-gen and in a very short period of time.  I looked at this project three months ago and thought, "not ready yet" and now I feel it is certainly ready.  Sure it will always need work and the more automation the better but this is top shelf guys... well done.
/W

**Comment by dakom** [comment] 2019-06-17 11:41
I'm having a bit of trouble trying to figure out how to pass more complex objects into the extension. for example something like this to allow vertex arrays via the "OES_vertex_array_object" extension, which should have the same signature as webgl2's native `create_vertex_array() / bind_vertex_array()`

it seems `create_vertex_array_oes()` is working fine, but when I try to pass that into `bind_vertex_array_oes()` I get errors.

Also tried different approaches (not using option, not using refs, etc.)

Any help is appreciated, thanks!

```
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_name = OesVertexArray)]
    pub type OesVertexArray;

    #[wasm_bindgen(method, getter, js_name = createVertexArrayOES)]
    pub fn create_vertex_array_oes(this: &OesVertexArray) -> Option<WebGlVertexArrayObject>;

    #[wasm_bindgen(method, js_name = bindVertexArrayOES)]
    pub fn bind_vertex_array_oes(this: &OesVertexArray, target:Option<&WebGlVertexArrayObject>);

}
```

**Comment by alexcrichton** [comment] 2019-06-17 12:33
@dakom can you open a new issue with details as well to the error you're seeing? Some code to reproduce would also be great!

**Comment by dakom** [comment] 2019-06-17 13:31
Nevermind - I see this extension is actually bundled as part of web-sys now :)

https://docs.rs/web-sys/0.3.23/web_sys/struct.OesVertexArrayObject.html
