### ISSUE TITLE
No way to access CryptoKeyPair properties

### ISSUE THREAD

**Issue by bakape** [rustwasm/wasm-bindgen#2092] opened 2020-04-19 01:47 UTC
### Describe the Bug

The `CryptoKeyPair` type only has property setters `private_key()` and `public_key()`. There are no methods to access the existing property values. This conflicts with the actual specified interface.

### Expected Behavior

`CryptoKeyPair` should provide both setter and getter methods.

### Additional Context

Spec: https://www.w3.org/TR/WebCryptoAPI/#keypair
Docs: https://developer.mozilla.org/en-US/docs/Web/API/CryptoKeyPair

**Comment by Pauan** [comment] 2020-04-19 02:41
I think this is the first time I've seen a dictionary that is actually returned by an API.

So we should probably change the dictionaries to no longer be builders, but instead have a more normal API.

**Comment by Pauan** [comment] 2020-04-19 02:44
(In the meantime you can workaround this by using `Reflect::get(&foo, &JsValue::from("privateKey"))`)

**Comment by bakape** [comment] 2020-04-19 22:11
Yes, already doing that.

**Comment by eminence** [comment] 2021-03-14 05:53
CC #1793

**Comment by daxpedda** [comment] 2023-08-11 15:19
Duplicate of #1793.

**Closed by daxpedda** 2023-08-11 15:19 UTC
Labels: bug, web-sys, breaking-change
