### ISSUE TITLE
Online example is broken

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rustwasm/wasm-bindgen#1318] opened 2019-03-06 14:11 UTC
The documentation page https://rustwasm.github.io/wasm-bindgen/examples/hello-world.html has a link ["view the compiled example online"](https://rustwasm.github.io/wasm-bindgen/exbuild/hello_world/).

This example does not work.

### To reproduce
1. Open https://rustwasm.github.io/wasm-bindgen/exbuild/hello_world/ in your browser.

### Expected behavior
Hello world alert or whatever.

### Actual behavior
Blank page, nothing happens. In the JS console there is the following message:
```
TypeError: Cannot read property '__wbindgen_malloc' of undefined
    at passStringToWasm (hello_world.js:66)
    at Module.greet (hello_world.js:77)
    at rust.then.m (index.js:7)
```

**Comment by alexcrichton** [comment] 2019-03-06 15:56
Thanks for the report! This was caused by https://github.com/rustwasm/wasm-bindgen/pull/1295 due to its repurposing and breaking of the `--browser` flag unfortunately, although this breakage was unexpected. I'll see if I can take a look at a fix.

**Comment by alexcrichton** [comment] 2019-03-07 16:14
Ok should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/1328!

**Closed** 2019-03-07 21:25 UTC
Labels: bug
