### ISSUE TITLE
dyn keyword required on 0.2.85

### ISSUE THREAD

**Issue by bobbobbio** [rustwasm/wasm-bindgen#3450] opened 2023-05-24 05:27 UTC
Starting with 0.2.85, in at least this one particular instance the `wasm_bindgen` macro seems to need the dyn keyword to compile correctly, and otherwise it gives a strange error.  For specifics see this compilation error with stdweb https://github.com/koute/stdweb/issues/427

I guess this is a breaking change but I'm not sure if this was intentional or not. I think the dyn keyword isn't required on all editions, but I'm not sure what editions are suppose to be supported. 

If the answer is stdweb just needs to be updated, then this can be closed.

**Comment by daxpedda** [comment] 2023-05-24 08:05
Duplicate of https://github.com/rustwasm/wasm-bindgen/issues/3415.

The problem is `syn` in this case, it correctly requires to use the `dyn` keyword when writing trait objects like this. This happened because of the upgrade to v2 of `syn`, so there is nothing we, as in `wasm-bindgen`, can really do here. This should be fixed in `stdweb`.

**Closed** 2023-05-24 08:05 UTC
Labels: bug
