### ISSUE TITLE
web_sys: Dictionaries don't have getters

### ISSUE THREAD

**Issue by rozbb** [rustwasm/wasm-bindgen#2921] opened 2022-06-01 21:58 UTC
### Describe the Bug

`dictionary` types from WebIDL do not have getters. You can only mutate dictionaries, and never read them. This is weird, considering how they're often used as event types or return types.

### Steps to Reproduce

Example: [`AudioDecoderSupport`](https://docs.rs/web-sys/0.3.57/web_sys/struct.AudioDecoderSupport.html) has no getters, despite being [defined](https://w3c.github.io/webcodecs/#config-support-info) as a return type to indicate to the caller which formats are supported. defined here  has no getters 

### Expected Behavior

`config(&self) -> AudioDecoderConfig` should be a getter

`set_config(&mut self, val: &AudioDecoderConfig)` should be a setter

### Actual Behavior

`config(&mut self, val: &AudioDecoderConfig)` is the only function available regarding the underlying `config` field, and it is a setter.

### Additional Context

[This](https://github.com/rustwasm/wasm-bindgen/blob/cbcf3e78ac1e17884cceb855fced173ddde37020/crates/webidl/src/generator.rs#L658-L673=) is the generating code. I've dumped several hours into modifying it to generate a setter, but I've failed so far. My main issue is **how do you generically convert the a `JsValue` from `js_sys::Reflect::get` into the appropriate return type?** There are lots of special cases that work but it's unclear how to do this generically. E.g., how do I turn a `JsValue` into an `Option<i32>`?

Very stumped here, but willing to do work to make a PR. Please comment with pointers and I'll be on it.

**Comment by daxpedda** [comment] 2024-06-12 12:42
Duplicate of #1793.

> My main issue is **how do you generically convert the a `JsValue` from `js_sys::Reflect::get` into the appropriate return type?** There are lots of special cases that work but it's unclear how to do this generically. E.g., how do I turn a `JsValue` into an `Option<i32>`?

Probably through [`JsValue::as_f64()`](https://docs.rs/wasm-bindgen/latest/wasm_bindgen/struct.JsValue.html#method.as_f64), but this shouldn't be a concern anymore since #3898.

**Closed by daxpedda** 2024-06-12 12:42 UTC
Labels: bug
