### ISSUE TITLE
WebGL example fails with unexpected section: <unknown> @+2824

### ISSUE THREAD

**Issue by bwasty** [rustwasm/wasm-bindgen#1267] opened 2019-02-17 17:25 UTC
The [WebGL Example](https://rustwasm.github.io/wasm-bindgen/exbuild/webgl/) ([Guide Page](https://rustwasm.github.io/wasm-bindgen/examples/webgl.html#webgl-example)) fails with this error (Browser console):

```
CompileError: AsyncCompile: Wasm decoding failed: unexpected section: <unknown> @+2824
```

I also get the same error when I copy the code to my project that is based on `wasm-pack-template`.

**Comment by xtuc** [comment] 2019-02-17 17:41
Interesting, I'll try to repro it. What version of Webpack and webassemblyjs are you using? (Check npm ls).

**Comment by bwasty** [comment] 2019-02-17 17:57
`webpack@4.29.4`
`@webassemblyjs/ast@1.8.2` (same version also for all other webassemblyjs packages)

Before upgrading to webpack@4.29.4 I had another similar error - the same as here: https://github.com/rustwasm/wasm-bindgen/issues/1251.

**Comment by alexcrichton** [comment] 2019-02-19 15:32
@bwasty can you test out the latest version of wasm-pack and NPM dependencies as well to see if the issue is fixed now?

**Comment by bwasty** [comment] 2019-02-19 17:45
@alexcrichton No change with 
wasm-pack 0.6.0

webpack@4.29.5
webassemblyjs/*@1.8.3

wasm-bindgen v0.2.37

**Comment by alexcrichton** [comment] 2019-02-19 19:47
Oh sorry @bwasty I misunderstood, this is indeed published live and I can see it myself!

@xtuc it looks like webpack may be producing an invalid JS file?

**Comment by xtuc** [comment] 2019-02-20 16:42
Indeed, Webpack's transformation breaks the Wasm module.

**Comment by sendilkumarn** [comment] 2019-02-24 06:14
@bwasty This will work if you remove the `start`. We are working on a fix now at https://github.com/xtuc/webassemblyjs/pull/493

**Comment by alexcrichton** [comment] 2019-02-28 15:33
Looks like this is now fixed, thanks @xtuc and @sendilkumarn!

**Closed by alexcrichton** 2019-02-28 15:33 UTC
