### ISSUE TITLE
Index 114 is out of range for a slice of length 33

### ISSUE THREAD

**Issue by dvc94ch** [rustwasm/wasm-bindgen#1368] opened 2019-03-19 17:36 UTC
### Describe the Bug
Try to build the fetch example results in:
```sh
wasm-bindgen/examples/fetch# wasm-bindgen ../../target/wasm32-unknown-unknown/release/fetch.wasm --out-dir pkg
thread 'main' panicked at 'index 114 out of range for slice of length 33', src/libcore/slice/mod.rs:2413:5
stack backtrace:
   0:     0x556099e47dd3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h3240831da26d7429
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x556099e43cfb - std::sys_common::backtrace::_print::h10e229fc9a8968d4
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x556099e46a86 - std::panicking::default_hook::{{closure}}::hdef40542ded4742e
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x556099e46819 - std::panicking::default_hook::hc72e577a409fc8f6
                               at src/libstd/panicking.rs:211
   4:     0x556099e4718f - std::panicking::rust_panic_with_hook::hb995d468d920d99f
                               at src/libstd/panicking.rs:474
   5:     0x556099e46d11 - std::panicking::continue_panic_fmt::h755fff74926f77ab
                               at src/libstd/panicking.rs:381
   6:     0x556099e46bf5 - rust_begin_unwind
                               at src/libstd/panicking.rs:308
   7:     0x556099e5cb7c - core::panicking::panic_fmt::h4753dd20b4122891
                               at src/libcore/panicking.rs:85
   8:     0x556099e5ceb5 - core::slice::slice_index_len_fail::he7fd818053ea42c4
                               at src/libcore/slice/mod.rs:2413
   9:     0x556099ccad95 - <&'src str as wasm_bindgen_cli_support::decode::Decode<'src>>::decode::h9a5dfc3266fa7fa0
  10:     0x556099ce8808 - <alloc::vec::Vec<T> as wasm_bindgen_cli_support::decode::Decode<'src>>::decode::h761d4ebba05688b5
  11:     0x556099ccbcc9 - <wasm_bindgen_cli_support::decode::Export<'a> as wasm_bindgen_cli_support::decode::Decode<'a>>::decode::h543650a03c396272
  12:     0x556099ce7c6d - <alloc::vec::Vec<T> as wasm_bindgen_cli_support::decode::Decode<'src>>::decode::h2dadeda570a2fcd0
  13:     0x556099ccb517 - <wasm_bindgen_cli_support::decode::Program<'a> as wasm_bindgen_cli_support::decode::Decode<'a>>::decode::h685039f6c3e0265b
  14:     0x556099ca41e7 - wasm_bindgen_cli_support::Bindgen::_generate::h1c9cddd6efb1de9d
  15:     0x556099c8f8ec - wasm_bindgen::main::h27c938c3abf1b1b4
  16:     0x556099c8b982 - std::rt::lang_start::{{closure}}::hdae04d3e30404500
  17:     0x556099e46b92 - std::panicking::try::do_call::ha9765cb9dd399b79
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:293
  18:     0x556099e4a629 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  19:     0x556099e4775c - std::rt::lang_start_internal::hfd158b8eda29dcb4
                               at src/libstd/panicking.rs:272
                               at src/libstd/panic.rs:388
                               at src/libstd/rt.rs:48
  20:     0x556099c8faf1 - main
  21:     0x7fd9d340e222 - __libc_start_main
  22:     0x556099c8b19d - _start
  23:                0x0 - <unknown>
```

I was actually trying to reproduce this, which may or may not be a bug:
```
wasm-pack test --chrome
[INFO]: Checking for the Wasm target...
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running /home/dvc/block/rust-ipfs-api/target/wasm32-unknown-unknown/debug/deps/ipfs_api-373ed5817b5471d6.wasm
running 1 test                                    

panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(ReferenceError: Request is not defined
        ReferenceError: Request is not defined
    at module.exports.__widl_f_new_with_str_and_init_Request (/home/dvc/block/rust-ipfs-api/target/wasm32-unknown-unknown/wbg-tmp/wasm-bindgen-test.js:374:34)
    at web_sys::Request::new_with_str_and_init::h96df232b6aa56732 (wasm-function[1056]:264)
    at ipfs_api::client::IpfsClient::build_base_request::h2d6d68c7582a91ca (wasm-function[438]:1337)
    at ipfs_api::client::IpfsClient::request_raw::h455820499c1b700d (wasm-function[372]:155)
    at ipfs_api::client::IpfsClient::request::h09748655457922b6 (wasm-function[1927]:89)
    at ipfs_api::client::IpfsClient::version::h9d589c1c7bea8f97 (wasm-function[2837]:89)
    at ipfs_api::client::tests::version::h7b983133068c92fc (wasm-function[1314]:69)
    at core::ops::function::FnOnce::call_once::he9c7540f6e1d875b (wasm-function[6913]:22)
    at wasm_bindgen_test::__rt::Context::execute_sync::{{closure}}::h9be853c78f22c21d (wasm-function[4754]:22)
    at <futures::future::lazy::Lazy<F, R>>::get::hb6eac3ea543d4a0e (wasm-function[673]:361))', src/libcore/result.rs:997:5

Stack:

Error
    at module.exports.__wbg_new_59cb74e423758ede (/home/dvc/block/rust-ipfs-api/target/wasm32-unknown-unknown/wbg-tmp/wasm-bindgen-test.js:349:30)
    at console_error_panic_hook::Error::new::h14b33245f0ca77ad (wasm-function[3227]:34)
    at console_error_panic_hook::hook_impl::h0226ef43fcd8b5e1 (wasm-function[1322]:100)
    at console_error_panic_hook::hook::hacd428aa039701bf (wasm-function[6267]:38)
    at core::ops::function::Fn::call::h81c6e3912c273e32 (wasm-function[5449]:45)
    at std::panicking::rust_panic_with_hook::h8d2e0791cb113657 (wasm-function[1751]:265)
    at std::panicking::continue_panic_fmt::h27e8e13b3cc257cb (wasm-function[3595]:116)
    at rust_begin_unwind (wasm-function[7710]:3)
    at core::panicking::panic_fmt::h4753dd20b4122891 (wasm-function[5575]:70)
    at core::result::unwrap_failed::h6319b8b1a1b4f180 (wasm-function[1503]:325)


test ipfs_api::client::tests::version ... FAIL
```

**Comment by alexcrichton** [comment] 2019-03-19 18:55
Thanks for the report! I think this is probably a duplicate of https://github.com/rustwasm/wasm-bindgen/issues/1227 unfortunately so I'm going to close in favor of that. Currently the examples aren't directly runnable as-is from this repository, but if you copy them out they should work!

**Closed by alexcrichton** 2019-03-19 18:55 UTC
Labels: bug
