### ISSUE TITLE
Function argument names are lost in .d.ts files

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rustwasm/wasm-bindgen#1327] opened 2019-03-07 15:58 UTC
### To reproduce:
1. Check out the recent version:
   ```
   git clone git@github.com:rustwasm/wasm-bindgen.git
   cd wasm-bindgen
   git checkout eaaf3461
   ```
3. Run without-a-bundler example:
   ```
   cd .\examples\without-a-bundler\
   cargo build --target wasm32-unknown-unknown --release
   mkdir pkg
   cargo run --manifest-path ../../crates/cli/Cargo.toml --bin wasm-bindgen -- ../../target/wasm32-unknown-unknown/release/without_a_bundler.wasm --out-dir pkg --browser
   ```
These commands are from [build.sh](https://github.com/rustwasm/wasm-bindgen/blob/master/examples/without-a-bundler/build.sh), except I was running them on Windows.

4. Examine `pkg/*.d.ts` files.

### Expected

These files to contain meaningful function signatures like `function add(a: number, b: number): number`.

### Actual

The file `pkg/without_a_bundler_bg.d.ts` is as expected.
The file `pkg/without_a_bundler.d.ts`, however, contains the following:
```typescript
/* tslint:disable */
/**
* @returns {void} 
*/
export function main(): void;
/**
* @param {number} arg0 
* @param {number} arg1 
* @returns {number} 
*/
export function add(arg0: number, arg1: number): number;
```

Argument names are lost and replaced with `arg0`, `arg1`.

---------------------

It is important for the latter file to contain useful function signatures, because that's the definition file that will be used by TypeScript when importing the wrapper module `without_a_bundler.js`.

**Comment by alexcrichton** [comment] 2019-03-07 16:27
Thanks for the report! I think this is a duplicate of https://github.com/rustwasm/wasm-bindgen/issues/1129 so I'm going to close this in favor of that

**Closed by alexcrichton** 2019-03-07 16:27 UTC
Labels: bug
