### ISSUE TITLE
Generated binding code does not free malloc'd data after passed to Rust if it's a Vec<u8>

### ISSUE THREAD

**Issue by KenanSulayman** [rustwasm/wasm-bindgen#1515] opened 2019-05-04 23:12 UTC
As opposed to the generated code when accepting a `&str`, wasm-bindgen will not free `Vec<u8>` aka Uint8Array after it has been passed to Rust.

We investigated this issue after several customers reported a Chrome crash related to memory exhaustion and found big `Uint8Array` passed to the WebAssembly module to keep growing the memory use, eventually running into memory issues.

---

Example code:

```
#[wasm_bindgen]
pub fn process(data: String) -> String {
    process_bytes(data.to_string().to_vec())
}
```

Generated binding code:

```
__exports.process = function(data) {
    const ptr0 = passStringToWasm(data);
    const len0 = WASM_VECTOR_LEN;
    const retptr = globalArgumentPtr();
    try {
        wasm.process(retptr, ptr0, len0);
        const mem = getUint32Memory();
        const rustptr = mem[retptr / 4];
        const rustlen = mem[retptr / 4 + 1];

        const realRet = getStringFromWasm(rustptr, rustlen).slice();
        wasm.__wbindgen_free(rustptr, rustlen * 1);
        return realRet;
    } finally {
        wasm.__wbindgen_free(ptr0, len0 * 1);
    }
}
```

---

Note how `ptr0` (`const ptr0 = passStringToWasm(data);`) is freed in the `finally` block at the end of the method: `wasm.__wbindgen_free(ptr0, len0 * 1);`. That said, the `return realRet;` in the `try` block will probably prevent `ptr0` from ever being freed in the `finally` block.

Compare the output when expecting a `Vec<u8>`:

---

Example code:

```
#[wasm_bindgen]
pub fn process(data: Vec<u8>) -> String {
    process_bytes(data)
}
```

Generated binding code:

```
__exports. process = function(data) {
    const ptr0 = passArray8ToWasm(data);
    const len0 = WASM_VECTOR_LEN;
    const retptr = globalArgumentPtr();
    wasm.process(retptr, ptr0, len0);
    const mem = getUint32Memory();
    const rustptr = mem[retptr / 4];
    const rustlen = mem[retptr / 4 + 1];

    const realRet = getStringFromWasm(rustptr, rustlen).slice();
    wasm.__wbindgen_free(rustptr, rustlen * 1);
    return realRet;
}
```

---

`ptr0` is allocated (`const ptr0 = passArray8ToWasm(data);`) but never freed.

**Comment by devsnek** [comment] 2019-05-05 00:07
> That said, the return realRet; in the try block will probably prevent ptr0 from ever being freed in the finally block.

Just to clarify, the finally block runs even if there's a return. It's quite an odd semantic in js.

```js
> function a() { try { return 'returned'; } finally { console.log('finally') } }
undefined
> a()
'finally'
'returned'
>
```

**Comment by devsnek** [comment] 2019-05-05 00:21
seems the issue is that the finally block doesn't get emitted because this condition is false: https://github.com/rustwasm/wasm-bindgen/blob/d382ad72a3c1fa8c221b76c072b5ba86945c83a3/crates/cli-support/src/js/js2rust.rs#L190

i guess it should also take into account things that get turned into references even if they aren't originally, like views over uint8arrays?

**Comment by ibaryshnikov** [comment] 2019-05-05 16:42
Thanks for your report!
I've compiled several examples to clarify the memory management.
First is about `String`
```rust
#[wasm_bindgen]
pub fn pass_string(s: String) -> String {
    s.clone()
}
```
generated js is
```javascript
module.exports.pass_string = function(s) {
    const ptr0 = passStringToWasm(s);
    const len0 = WASM_VECTOR_LEN;
    const retptr = globalArgumentPtr();
    wasm.pass_string(retptr, ptr0, len0);
    const mem = getUint32Memory();
    const rustptr = mem[retptr / 4];
    const rustlen = mem[retptr / 4 + 1];

    const realRet = getStringFromWasm(rustptr, rustlen).slice();
    wasm.__wbindgen_free(rustptr, rustlen * 1);
    return realRet;
};
```
And in the webassembly there is a line
```wat
call $__rust_dealloc
```
Now let's go through the details what's going on here.
`fn pass_string(s: String)` means we pass the ownership from JavaScript to Rust. And the Rust will be responsible for deallocating the memory inside the `.wasm` binary. The return type of the function `-> String` means that the ownership of a result is passed to JavaScript. That's why there's `wasm.__wbindgen_free(rustptr, rustlen * 1);` in generated `.js` file.

The second example is about `&str`
```rust
#[wasm_bindgen]
pub fn pass_str(s: &str) -> String {
    s.to_owned()
}
```
```javascript
module.exports.pass_str = function(s) {
    const ptr0 = passStringToWasm(s);
    const len0 = WASM_VECTOR_LEN;
    const retptr = globalArgumentPtr();
    try {
        wasm.pass_str(retptr, ptr0, len0);
        const mem = getUint32Memory();
        const rustptr = mem[retptr / 4];
        const rustlen = mem[retptr / 4 + 1];

        const realRet = getStringFromWasm(rustptr, rustlen).slice();
        wasm.__wbindgen_free(rustptr, rustlen * 1);
        return realRet;

    } finally {
        wasm.__wbindgen_free(ptr0, len0 * 1);
    }
};
```
Here the argument is a reference, `&str`. That means that the ownership stays in JavaScript world. That's why there are two calls of `__wbindgen_free` in generated `.js`: one for the argument and another for the returned value.
The `Vec<u8>` behaves exacly like `String` from the first example.

**Comment by KenanSulayman** [comment] 2019-05-05 16:59
Thanks for your elaborate reply!

Passing the ownership to the WebAssembly module something I had considered, but it seemed semantically unintuitive as the difference between _extern-alloc-extern-free_ and _extern-alloc-intern-free_ introduces needless tight-coupling to the underlying behaviour of the WebAssembly module (aka complexity).

What I mean is that `#[wasm_bindgen]` nearly completely abstracts the malloc and JS-wasm boundary logic away from the developer, and therefore I'd consider it to be appropriate to ensure the passed data to be freed at the same location where it was allocated -- given that the allocation wasn't ever explicitly coded by the developer, but by the abstraction logic.

That said, it would lessen my OCD if both behaviours were reduced into a single facility either inside the WebAssembly module, or, because the handling of the passed-in data always happens outside of the WebAssembly boundary, even better, in the JS orchestration code. At least that would make debugging easier, because the freeing logic would be located in a deterministic location.

🐝

**Comment by alexcrichton** [comment] 2019-05-06 15:29
Thanks for the report @KenanSulayman! Can you gist the code that you're running into this with? The description in the OP disagrees with what @ibaryshnikov [posted above](https://github.com/rustwasm/wasm-bindgen/issues/1515#issuecomment-489442651) in terms of the bindings generated for `fn(String) -> String`, so I'm wondering if a typo snuck in by accident somewhere?

**Comment by KenanSulayman** [comment] 2019-05-06 16:00
@alexcrichton that's accurate, it was meant to say `pub fn process(data: &str) -> String {`.

The actual code involved is:

```typescript
// outside rust
const buf = new Uint8Array(target.result as ArrayBuffer);
const docs_raw = this.props.parser.process(buf);
```

```rust
// inside rust
#[wasm_bindgen]
pub fn process(data: &[u8]) -> String {
    types::StatusDTO::from_data(data).to_string()
}
```

The original implementation read as follows:

```rust
// inside rust
#[wasm_bindgen]
pub fn process(data: Vec<u8>) -> String {
    types::StatusDTO::from_data(&data).to_string()
}
```

Confusion was caused by the significant difference of freeing behaviour`&[u8]` vs `Vec<u8>`.

**Comment by alexcrichton** [comment] 2019-05-06 16:07
Ah ok thanks for the clarification, that makes sense! So reviewing the generated code again I don't think there's any leaks from the implicit transfer of the bytes and/or string. Are you sure that this is where the leak is coming from? There's a few different ways that memory can be leaked in the wasm heap, and I've also heard reports in the past where Chrome may have an internal wasm bug which causes applications to look like they OOM when it works in other browsers (like Firefox).

**Comment by ibaryshnikov** [comment] 2019-05-07 07:25
@alexcrichton my colleague once reported `RangeError: WebAssembly Instantiation: Out of memory: wasm memory`.  Is it the same thing you mentioned?

**Comment by KenanSulayman** [comment] 2019-05-07 07:34
@ibaryshinkov yes, that is exactly the same issue that led us to investigate possible leaks

**Comment by alexcrichton** [comment] 2019-05-08 15:02
Googling around that error message, perhaps https://github.com/brave/brave-browser/issues/3366 can shed some light on the issue too?

**Comment by ibaryshnikov** [comment] 2019-06-04 10:46
@alexcrichton it's not a wasm-bindgen issue I guess?

**Comment by KenanSulayman** [comment] 2019-06-04 12:54
I would close it, but I also think it's useful to have it around to update it when those memory issues aren't an issue anymore. Although it could use its own tracking issue.

**Comment by alexcrichton** [comment] 2019-06-04 14:14
Ah yeah I'm going to close this because I don't think it's a wasm-bindgen issue, but I think unfortunately the root cause wasn't learned. If we get around to that we can certainly document it in wasm-bindgen!

**Closed by alexcrichton** 2019-06-04 14:14 UTC
Labels: bug
