### ISSUE TITLE
Feedback on running examples: wasm-bindgen versioning confusion

### ISSUE THREAD

**Issue by gregtatum** [rustwasm/wasm-bindgen#975] opened 2018-10-18 12:11 UTC
Thanks for all the work on making wasm easier to use on the web! I have some feedback on my onboarding process, hopefully it's helpful.

I felt confused trying to figure out how to get [one of the examples to run](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/canvas). I had tried around a month ago unsuccessfully to get the examples to run, mainly because not all of the packages were published yet. I tried another attempt this morning to port of the canvas example. I started the somewhat tedious process of copying over all the files from the examples, and attempting to update every relative path I encountered to use the crate's version.

I finally got everything going, and tried to run the `build.sh` file.

On this line:

```
wasm-bindgen ./target/wasm32-unknown-unknown/debug/canvas.wasm --out-dir .
```

I encountered the following error:

```
error: failed to extract wasm-bindgen custom sections
	caused by:

it looks like the Rust project used to create this wasm file was linked against
a different version of wasm-bindgen than this binary:

  rust wasm file: 0.2.25
     this binary: 0.2.15

Currently the bindgen format is unstable enough that these two version must
exactly match, so it's required that these two version are kept in sync by
either updating the wasm-bindgen dependency or this binary. You should be able
to update the wasm-bindgen dependency with:

    cargo update -p wasm-bindgen

or you can update the binary with

    cargo install -f wasm-bindgen-cli

if this warning fails to go away though and you're not sure what to do feel free
to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!
```

I felt a bit confused by this error as it wasn't clear to me the mental model to how `wasm-bindgen` works. I wasn't sure specifically what `Rust project used to create this wasm file` and `different version of wasm-bindgen than this binary` were referring to. In my mental model (developed from using npm) I could add my dependencies to `Cargo.toml` and everything should just work.

I eventually figured out by running `type wasm-bindgen` that this was a globally installed dependency that had a version mismatch. I ran `cargo +nightly install wasm-bindgen-cli --force` to fix the issue, but now I'm left concerned of how I have the correct version of `wasm-bindgen-cli` between different projects. Most likely this comes from my usage of `npm` and not having to think about the global dependency environment. I kind of feel that I want my `wasm-bindgen-cli` to be installed and compiled using npm, that way I can ensure my versioning is correct local to my current project, unless there is some other mechanism that I'm missing.

**Comment by alexcrichton** [comment] 2018-10-18 13:56
Thanks for the report! While I'm glad we have this error it's true that it doesn't seem to have headed off too much confusion :(

The good news though is that the [`wasm-pack`](https://github.com/rustwasm/wasm-pack) project will automatically take care of these version dependencies for you, so you won't have to worry about seeing this error ever again!

I think that we'll eventually want to move all the wasm-bindgen examples and guides to using `wasm-pack` as well, and in general we're trying to move towards a world where `wasm-bindgen` is a low-level tool (like `ld`) which you don't really run by hand but is rather intended to be run by other tooling.

Do you think that'd solve the problem you're encountering? Are there perhaps easy wins we could get in the meantime though by improving the error message?

**Comment by gregtatum** [comment] 2018-10-18 16:19
Cool, I'm looking forward to all the goodness of `wasm-pack` then!

```
it looks like the Rust project used to create this wasm file was linked against
a different version of wasm-bindgen than this binary:

  rust wasm file: 0.2.25
     this binary: 0.2.15
```

I think the shortest term win here could be reword this comment a bit clearer. As a newbie, I didn't understand what everything was referring to. What's "the Rust project", is this my code? The linking and how everything works is a bit magical to me, so those words weren't really adding much meaning, as it's the first time I'm running it. Where are the two versions coming from? How do I fix it?

Essentially the answer was my `wasm-bindgen` executable on my path needs to match what was in my `Cargo.toml`, but that wasn't clear to me from this error without further investigations and trial/error.

**Comment by alexcrichton** [comment] 2018-10-19 01:49
It looks like you figured out eventually what the mismatch was, do you perhaps have a suggestion of what we could reword the message to? I think we should probably mention `wasm-pack` primarily  and then perhaps `cargo update` as well as `cargo install wasm-bindgen-cli`, but do you think that would be enough?

**Comment by DevinBayly** [comment] 2018-10-25 02:30
This issue is very similar to what I'm facing with the minor difference that `wasm-pack build` is triggering the compilation error. I'm unsure whether I need to somehow update the system wasm-bindgen, or make very clear in the cargo.toml that I'm trying to use the most recent wasm-bindgen. Thanks for your assistance. If this is actually an issue which should be dealt with separately I can make a new issue, but it seemed related. Sorry for the long post.

Here's the wasm-pack error output

  
  [1/9] Checking `rustc` version...
  [2/9] Checking crate configuration...
  [3/9] Adding WASM target...
  [4/9] Compiling to WASM...
  [5/9] Creating a pkg directory...
  [6/9] Writing a package.json...
  :-) [WARN]: Field 'description' is missing from Cargo.toml. It is not necessary, but recommended
  :-) [WARN]: Field 'repository' is missing from Cargo.toml. It is not necessary, but recommended
  :-) [WARN]: Field 'license' is missing from Cargo.toml. It is not necessary, but recommended
  [7/9] Copying over your README...
  [8/9] wasm-bindgen already installed...
| [9/9] Running WASM-bindgen...
wasm-bindgen failed to execute properly. stderr:

error: failed to extract wasm-bindgen custom sections
	caused by: 

it looks like the Rust project used to create this wasm file was linked against
a different version of wasm-bindgen than this binary:

  rust wasm file: 0.2.23 (e368e49af)
     this binary: 0.2.19 (d9bc0a317)

Currently the bindgen format is unstable enough that these two version must
exactly match, so it's required that these two version are kept in sync by
either updating the wasm-bindgen dependency or this binary. You should be able
to update the wasm-bindgen dependency with:

    cargo update -p wasm-bindgen

or you can update the binary with

    cargo install -f wasm-bindgen-cli

if this warning fails to go away though and you're not sure what to do feel free
to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!



Here are my cargo.toml and lock files for inspection, which I've already tried to patch.
## cargo.toml
[package]
name = "wasm-pack-tutorial"
version = "0.1.0"
authors = ["Your Name <baylyd@email.arizona.edu>"]

[lib]
crate-type = ["cdylib"]

[features]
default-features = ["console_error_panic_hook", "wee_alloc"]

[dependencies]
ndarray = "0.11.0"
js-sys = {git= "https://github.com/rustwasm/wasm-bindgen"}
cfg-if = "0.1.2"
wasm-bindgen = "0.2.20"
#{git = "https://github.com/rustwasm/wasm-bindgen",version = "^0.2"} # tried using this also, with the same problem

console_error_panic_hook = { version = "0.1.1", optional = true }

wee_alloc = { version = "0.4.1", optional = true }

[patch.crates-io]
wasm-bindgen = {git = "https://github.com/rustwasm/wasm-bindgen",version = "^0.2"}

## cargo.lock
[[package]]
name = "cfg-if"
version = "0.1.5"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "console_error_panic_hook"
version = "0.1.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "cfg-if 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "wasm-bindgen 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "either"
version = "1.5.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "itertools"
version = "0.7.8"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "either 1.5.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "itoa"
version = "0.4.3"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "js-sys"
version = "0.3.0"
source = "git+https://github.com/rustwasm/wasm-bindgen#e368e49af19174a6c012cf8238003a365fd04252"
dependencies = [
 "wasm-bindgen 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)",
]

[[package]]
name = "lazy_static"
version = "1.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "version_check 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "libc"
version = "0.2.43"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "log"
version = "0.4.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "cfg-if 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "matrixmultiply"
version = "0.1.14"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "rawpointer 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "memory_units"
version = "0.4.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "ndarray"
version = "0.11.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "itertools 0.7.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "matrixmultiply 0.1.14 (registry+https://github.com/rust-lang/crates.io-index)",
 "num-complex 0.1.43 (registry+https://github.com/rust-lang/crates.io-index)",
 "num-traits 0.1.43 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "num-complex"
version = "0.1.43"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "num-traits 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "num-traits"
version = "0.1.43"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "num-traits 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "num-traits"
version = "0.2.6"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "proc-macro2"
version = "0.4.20"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "unicode-xid 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "quote"
version = "0.6.8"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "proc-macro2 0.4.20 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "rawpointer"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "ryu"
version = "0.2.6"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde"
version = "1.0.79"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde_derive"
version = "1.0.79"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "proc-macro2 0.4.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "quote 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "syn 0.15.8 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "serde_json"
version = "1.0.32"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "itoa 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "ryu 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde 1.0.79 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "syn"
version = "0.14.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "proc-macro2 0.4.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "quote 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "unicode-xid 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "syn"
version = "0.15.8"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "proc-macro2 0.4.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "quote 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "unicode-xid 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "unicode-xid"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "unreachable"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "void 1.0.2 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "version_check"
version = "0.1.5"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "void"
version = "1.0.2"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "wasm-bindgen"
version = "0.2.19"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "wasm-bindgen-macro 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "wasm-bindgen"
version = "0.2.23"
source = "git+https://github.com/rustwasm/wasm-bindgen#e368e49af19174a6c012cf8238003a365fd04252"
dependencies = [
 "wasm-bindgen-macro 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)",
]

[[package]]
name = "wasm-bindgen-backend"
version = "0.2.19"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "lazy_static 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.4.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "proc-macro2 0.4.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "quote 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde_json 1.0.32 (registry+https://github.com/rust-lang/crates.io-index)",
 "syn 0.14.9 (registry+https://github.com/rust-lang/crates.io-index)",
 "wasm-bindgen-shared 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "wasm-bindgen-backend"
version = "0.2.23"
source = "git+https://github.com/rustwasm/wasm-bindgen#e368e49af19174a6c012cf8238003a365fd04252"
dependencies = [
 "lazy_static 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.4.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "proc-macro2 0.4.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "quote 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde_json 1.0.32 (registry+https://github.com/rust-lang/crates.io-index)",
 "syn 0.15.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "wasm-bindgen-shared 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)",
]

[[package]]
name = "wasm-bindgen-macro"
version = "0.2.19"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "quote 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "wasm-bindgen-macro-support 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "wasm-bindgen-macro"
version = "0.2.23"
source = "git+https://github.com/rustwasm/wasm-bindgen#e368e49af19174a6c012cf8238003a365fd04252"
dependencies = [
 "quote 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "wasm-bindgen-macro-support 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)",
]

[[package]]
name = "wasm-bindgen-macro-support"
version = "0.2.19"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "proc-macro2 0.4.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "quote 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "syn 0.14.9 (registry+https://github.com/rust-lang/crates.io-index)",
 "wasm-bindgen-backend 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)",
 "wasm-bindgen-shared 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "wasm-bindgen-macro-support"
version = "0.2.23"
source = "git+https://github.com/rustwasm/wasm-bindgen#e368e49af19174a6c012cf8238003a365fd04252"
dependencies = [
 "proc-macro2 0.4.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "quote 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "syn 0.15.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "wasm-bindgen-backend 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)",
 "wasm-bindgen-shared 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)",
]

[[package]]
name = "wasm-bindgen-shared"
version = "0.2.19"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "serde 1.0.79 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde_derive 1.0.79 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "wasm-bindgen-shared"
version = "0.2.23"
source = "git+https://github.com/rustwasm/wasm-bindgen#e368e49af19174a6c012cf8238003a365fd04252"
dependencies = [
 "serde 1.0.79 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde_derive 1.0.79 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "wasm-pack-tutorial"
version = "0.1.0"
dependencies = [
 "cfg-if 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "console_error_panic_hook 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "js-sys 0.3.0 (git+https://github.com/rustwasm/wasm-bindgen)",
 "ndarray 0.11.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "wasm-bindgen 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)",
 "wee_alloc 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "wee_alloc"
version = "0.4.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "cfg-if 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.43 (registry+https://github.com/rust-lang/crates.io-index)",
 "memory_units 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "unreachable 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "winapi"
version = "0.3.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "winapi-i686-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "winapi-x86_64-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "winapi-i686-pc-windows-gnu"
version = "0.4.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "winapi-x86_64-pc-windows-gnu"
version = "0.4.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[metadata]
"checksum cfg-if 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = "0c4e7bb64a8ebb0d856483e1e682ea3422f883c5f5615a90d51a2c82fe87fdd3"
"checksum console_error_panic_hook 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = "3798a10f11ad2f48fd6a0ffcbb73fd6cc4c43ec463179a436f2c4a779b54abdd"
"checksum either 1.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = "3be565ca5c557d7f59e7cfcf1844f9e3033650c929c6566f511e8005f205c1d0"
"checksum itertools 0.7.8 (registry+https://github.com/rust-lang/crates.io-index)" = "f58856976b776fedd95533137617a02fb25719f40e7d9b01c7043cd65474f450"
"checksum itoa 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)" = "1306f3464951f30e30d12373d31c79fbd52d236e5e896fd92f96ec7babbbe60b"
"checksum js-sys 0.3.0 (git+https://github.com/rustwasm/wasm-bindgen)" = "<none>"
"checksum lazy_static 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = "ca488b89a5657b0a2ecd45b95609b3e848cf1755da332a0da46e2b2b1cb371a7"
"checksum libc 0.2.43 (registry+https://github.com/rust-lang/crates.io-index)" = "76e3a3ef172f1a0b9a9ff0dd1491ae5e6c948b94479a3021819ba7d860c8645d"
"checksum log 0.4.5 (registry+https://github.com/rust-lang/crates.io-index)" = "d4fcce5fa49cc693c312001daf1d13411c4a5283796bac1084299ea3e567113f"
"checksum matrixmultiply 0.1.14 (registry+https://github.com/rust-lang/crates.io-index)" = "cac1a66eab356036af85ea093101a14223dc6e3f4c02a59b7d572e5b93270bf7"
"checksum memory_units 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = "8452105ba047068f40ff7093dd1d9da90898e63dd61736462e9cdda6a90ad3c3"
"checksum ndarray 0.11.2 (registry+https://github.com/rust-lang/crates.io-index)" = "0e3d24c5ba54015d7d5203ca6f00d4cc16c71042bf7f7be26f091236f390a16a"
"checksum num-complex 0.1.43 (registry+https://github.com/rust-lang/crates.io-index)" = "b288631d7878aaf59442cffd36910ea604ecd7745c36054328595114001c9656"
"checksum num-traits 0.1.43 (registry+https://github.com/rust-lang/crates.io-index)" = "92e5113e9fd4cc14ded8e499429f396a20f98c772a47cc8622a736e1ec843c31"
"checksum num-traits 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)" = "0b3a5d7cc97d6d30d8b9bc8fa19bf45349ffe46241e8816f50f62f6d6aaabee1"
"checksum proc-macro2 0.4.20 (registry+https://github.com/rust-lang/crates.io-index)" = "3d7b7eaaa90b4a90a932a9ea6666c95a389e424eff347f0f793979289429feee"
"checksum quote 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)" = "dd636425967c33af890042c483632d33fa7a18f19ad1d7ea72e8998c6ef8dea5"
"checksum rawpointer 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = "ebac11a9d2e11f2af219b8b8d833b76b1ea0e054aa0e8d8e9e4cbde353bdf019"
"checksum ryu 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)" = "7153dd96dade874ab973e098cb62fcdbb89a03682e46b144fd09550998d4a4a7"
"checksum serde 1.0.79 (registry+https://github.com/rust-lang/crates.io-index)" = "84257ccd054dc351472528c8587b4de2dbf0dc0fe2e634030c1a90bfdacebaa9"
"checksum serde_derive 1.0.79 (registry+https://github.com/rust-lang/crates.io-index)" = "31569d901045afbff7a9479f793177fe9259819aff10ab4f89ef69bbc5f567fe"
"checksum serde_json 1.0.32 (registry+https://github.com/rust-lang/crates.io-index)" = "43344e7ce05d0d8280c5940cabb4964bea626aa58b1ec0e8c73fa2a8512a38ce"
"checksum syn 0.14.9 (registry+https://github.com/rust-lang/crates.io-index)" = "261ae9ecaa397c42b960649561949d69311f08eeaea86a65696e6e46517cf741"
"checksum syn 0.15.8 (registry+https://github.com/rust-lang/crates.io-index)" = "356d1c5043597c40489e9af2d2498c7fefc33e99b7d75b43be336c8a59b3e45e"
"checksum unicode-xid 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = "fc72304796d0818e357ead4e000d19c9c174ab23dc11093ac919054d20a6a7fc"
"checksum unreachable 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = "382810877fe448991dfc7f0dd6e3ae5d58088fd0ea5e35189655f84e6814fa56"
"checksum version_check 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = "914b1a6776c4c929a602fafd8bc742e06365d4bcbe48c30f9cca5824f70dc9dd"
"checksum void 1.0.2 (registry+https://github.com/rust-lang/crates.io-index)" = "6a02e4885ed3bc0f2de90ea6dd45ebcbb66dacffe03547fadbb0eeae2770887d"
"checksum wasm-bindgen 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)" = "6dbe59a66beb5f8f5cfb2b5fa7a672173b965fdf0e16cdff89baaa58e48e86ff"
"checksum wasm-bindgen 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)" = "<none>"
"checksum wasm-bindgen-backend 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)" = "9c9d0c8af93cda64799f966579fd2f42147274f604a12fac1f192af3f8f1cbe6"
"checksum wasm-bindgen-backend 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)" = "<none>"
"checksum wasm-bindgen-macro 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)" = "66e07adde3a57d1c18c8a8171195c0d52ad03b1043a934377620582f2aacc7eb"
"checksum wasm-bindgen-macro 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)" = "<none>"
"checksum wasm-bindgen-macro-support 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)" = "4816b9f9ea6637343310854d5068d71d7c90482ead3d90ec0e57f916b2b6869f"
"checksum wasm-bindgen-macro-support 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)" = "<none>"
"checksum wasm-bindgen-shared 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)" = "13d45ad95e1245d26ba841fddbaf162bccb65bee7b8cca57d43b5ef5c58bdd93"
"checksum wasm-bindgen-shared 0.2.23 (git+https://github.com/rustwasm/wasm-bindgen)" = "<none>"
"checksum wee_alloc 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = "27875be1daf838fa18f3e94fd19fd12638e34615b42f56da2610c8f46be80cc6"
"checksum winapi 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = "92c1eb33641e276cfa214a0522acad57be5c56b10cb348b3c5117db75f3ac4b0"
"checksum winapi-i686-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = "ac3b87c63620426dd9b991e5ce0329eff545bccbbb34f3be09ff6fb6ab51b7b6"
"checksum winapi-x86_64-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = "712e227841d057c1ee1cd2fb22fa7e5a5461ae8e48fa2ca79ec42cfc1931183f"

**Comment by fitzgen** [comment] 2018-10-25 09:36
@DevinBayly that error is what happens when the wasm-bindgen CLI tool's version doesn't match the version of the crate used. wasm-pack will automatically ensure that the correct versions are used if you're using wasm-pack >=0.5.0 and *not* using the `no-install` mode. Are you satisfying both of those things?

**Comment by DevinBayly** [comment] 2018-10-25 16:57
I believe I wasn't satisfying all that, so I left that crate and started over. before making a new project I ran 
``` 
cargo install -f wasm-bindgen-cli
cargo install -f wasm-pack 
```
I don't know whether the above step was crucial to the solution, because at that point when I removed the git links in my cargo.toml wasm-pack build ran smoothly.

**Comment by alexcrichton** [comment] 2019-04-16 18:04
I'm gonna go ahead and close this in favor of https://github.com/rustwasm/wasm-bindgen/issues/1227 which I believe is the underlying issue here

**Closed by alexcrichton** 2019-04-16 18:04 UTC
